- asyncua/client/client.py
The renewal loop  was sleeping for hundreds of hours
> Fix session renewal bug.

- asyncua/server/history_sql.py
- setup.py
Fixes #28 
I removed the contextmanager dependency. Using the sqlite3 shortcut methods described here [https://docs.python.org/3/library/sqlite3.html#using-sqlite3-efficiently](https://docs.python.org/3/library/sqlite3.html#using-sqlite3-efficiently) i removed explicit creation of the cursor altogether.
> removed async_contextmanager dependency, use sqlite3 shortcut methods

- asyncua/common/subscription.py
- asyncua/server/internal_server.py
- tests/test_subscriptions.py
relates to #25 
Refactoring of common.subscription.modify_monitored_item - Scrutinizer reported that `item_to_change` was not defined for all paths.
New test for `modify_monitored_item`.
Fixes a bug in internal_server.modify_monitored_items (has to be a coroutine).
> refactored subscription.modify_monitored_item

- asyncua/client/client.py
- asyncua/client/ua_client.py
- examples/server-minimal.py
I removed the callback parameter from UASocketProtocol._send_request(). Now only the returned `Future` can be used which simplifies the code.
Fixed some bugs in untested methods e.g. `UaClient.register_nodes`.
Cleaned up the server-minimal example. We should not use the `*` binding for host names as it does not work on windows. `0.0.0.0` should work for both platforms?
> UaClient refactoring

- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/common/subscription.py
- asyncua/server/address_space.py
- asyncua/server/binary_server_asyncio.py
- asyncua/server/event_generator.py
- asyncua/server/internal_server.py
- asyncua/server/internal_session.py
- asyncua/server/internal_subscription.py
- asyncua/server/monitored_item_service.py
- asyncua/server/server.py
- asyncua/server/subscription_service.py
- asyncua/server/uaprocessor.py
- asyncua/server/users.py
- asyncua/ua/ua_binary.py
- asyncua/ua/uaerrors/_base.py
- tests/test_subscriptions.py
- tests/test_sync.py
- tests/test_unit.py
**preliminary - do not merge yet**
I worked on the client subscription publish mechanism. There is now less _fire and forget_ but the changes affect the  symmetry between client and server a bit (internally).
The `UaClient` now has a task that cyclically issues PublishRequests. `Subscription` no longer has to call the `publish()` method.
There is much more potential for simplification in the workings of `InternalSession`, `SubscriptionService`, `InternalSubscription`, `MonitoredItemService` ...
But before that i would like to try and draw a UML diagram, it is hard for me to keep that level of complexity in my mind.
This branch needs further testing and discussion. I may try to use it for some productive systems at work for testing.
> Refactored Subscription

- asyncua/client/ua_client.py
- asyncua/common/utils.py
- tests/test_subscriptions.py
Fixes #40
Fragmented data reception could lead to `UASocketProtocol` processing the same message twice which must not happen and leads to a `UaError` because of the repeated sequence number.
> Fix UASocketProtocol receive buffer

- asyncua/server/internal_session.py
- dev_requirements.txt
- tests/test_server.py
This PR fixes a bug where closing a client session will delete all subscriptions of all sessions on a server, rather than just the subscriptions for the particular client. 
It looks like `python-opcua` had this covered by keeping track of a list of subscriptions specific to the session and [only deleting those](https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/server/internal_server.py#L333). In this PR I add similar functionality back in.
This was tested locally by running two clients connected to the same server. Previously, each time a client would disconnect, subscriptions would get removed, and after this change, this doesn't happen. I've also added a unit test to multiple clients with subscriptions. I validated that this test fails on master and passes on this branch.
> Only remove subscriptions specific to a client when closing a session

- asyncua/client/client.py
Servers, for example servers created with the UA .NETStandard SDK, check the signature algorithm when activating a session. 
Until now the algorithm was always set to the sha1 uri in the client class. 
Basic256Sha256 needs the sha256 uri as signature algorithm. Connections will fail if the incorrect algorithm is set.
As the security_policies classes contain the property AsymmetricSignatureURI we can use that information in the activate_session method.
See example C# validation code here: [https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Stack/Opc.Ua.Core/Security/Constants/SecurityPolicies.cs#L325](https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Stack/Opc.Ua.Core/Security/Constants/SecurityPolicies.cs#L325)
> Set the correct client signature algorithm

- asyncua/client/ua_client.py
- asyncua/server/internal_session.py
- asyncua/server/internal_subscription.py
- asyncua/server/subscription_service.py
- asyncua/server/uaprocessor.py
- tests/conftest.py
- tests/test_subscriptions.py
On internal server subscriptions `InternalSubscription._not_acknowledged_results` kept growing onexternal data changes. This was a bug that was introduced in the #45 Subscription refactoring.
> Fix #71 (missing publish call in internal server subscriptions)

- setup.py
As per title. Production systems shouldn't need to have `pytest-runner` installed.
(Note: possibly a duplicated effort as branch `asyncua` has a different setup.py file which does not contain this problem)
> remove unnecessary production dependency into tests requirement

- asyncua/common/methods.py
- asyncua/server/address_space.py
- examples/server-methods.py
- tests/test_common.py
I occasionally run methods from my server that involve some I/O or other logic that doesn't execute relatively quickly, and therefore the server will block on these methods for a while if they are called synchronously. I have got around this in the past by running these methods in a thread and then emitting an event when it completes, but I thought it would make sense to implement the ability to run `async` methods directly. My goal is best demonstrated by example:
```python
@uamethod
async def func1(parent, value):
_logger.info(f"Starting async sleep for {value} seconds")
await asyncio.sleep(value)
_logger.info("Ending async sleep")
@uamethod
def func2(parent, value):
_logger.info(f"Starting sync sleep for {value} seconds")
time.sleep(value)
_logger.info("Ending sync sleep")
```
Before, …
> Allow Asynchronous Method Calls

- asyncua/common/copy_node_util.py
Hello,
I think this loop is dispensable in _read_and_copy_attrs function in copy_node_util file: 
```
for name in names:
results = await node_type.get_attributes(attrs)
```
> revmove dispensable loop

- asyncua/server/internal_subscription.py
As discussed in https://github.com/FreeOpcUa/opcua-asyncio/issues/93, the call to `publish_results` in `_trigger_publish` currently seems unreachable due to conflicting conditionals.
In this PR, I update the logic for publishing of a subscription to be the following:
* If the publishing interval of a subscription is non-zero, start a subscription loop task that publishes updates on the provided interval
* If the publishing interval of the subscription is zero, don't start a subscription loop task, and instead publish an update immediately when it is manually triggered.
In the future, do you think it would make sense to allow both immediate triggering and interval-based triggering? I think to allow that you'd need some locking to ensure that the immediate trigger doesn't clash with the …
> Fix immediate publishing

- asyncua/common/subscription.py
While running tests, I saw this `DeprecationWarning` come up:
```
...\opcua-asyncio\asyncua\common\subscription.py:210: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
if isinstance(nodes, collections.Iterable):
```
This change [was made in Python 3.3](https://docs.python.org/3.7/library/collections.abc.html#module-collections.abc), and since `opcua-asyncio` only support Python 3.6+, this should be a safe change.
> Resolve collections.Iterable DeprecationWarning for Python 3.8

- asyncua/sync.py
- tests/test_sync.py
Calling `sync.Server.get_node` raises an `AttributeError`.
This commit fixes the issue and adds a corresponding test.
> Fix Issue #108

- asyncua/server/internal_subscription.py
In https://github.com/FreeOpcUa/opcua-asyncio/pull/94, I made it so that you could have a 0ms publishing interval on your subscription. When you do this, the [`InternalSubscription` doesn't create a subscription task](https://github.com/FreeOpcUa/opcua-asyncio/blob/08861799d3413345dcc5b4ae387427739b864bad/asyncua/server/internal_subscription.py#L50-L51). Then, when the `InternalSubscription` is stopped, the `stop` function attempts to cancel the `InternalSubscription`s task, which doesn't exist, leading to an `AttributeError`.
This PR introduces a simple check to see if the task exists before cancelling it, and do nothing if the task doesn't exist.
This was tested with both a server and a client from this package. I subscribed to the server (with a 0ms subscription interval) with the …
> Don't cancel missing subscription task

- asyncua/common/subscription.py
Currently, the subscription cache is let inconsistent after a call to unsubscribe that contains multiple handles, this PR fixes that. 
Also adds a quicker noop path when the list of handles is empty to avoid unnecessary server calls.
> [subscription][monitored_items]: enhance client cache consistency

- asyncua/sync.py
I was starting to use the sync API to replace `python-opcua` in an application, but came across a few incompatibilities due to some missing methods in the sync API that did exist in `ua.Node`. I added these methods back to the API and my application is working equivalently to when it was using `python-opcua`. 
While adding these methods to the API, I also noticed that `read_value` had the wrong arguments (it took an extra positional argument that it shouldn't have), so I fixed that as well.
Is the goal to eventually expose the entire API for each object in this sync file?
> Add a few methods to sync Node API

- asyncua/sync.py
I noticed an issue where if I ran a process that periodically created new `asyncua.sync.Client` objects, I would eventually run out of file descriptors on that process, manifesting itself as a `OSError: [Errno 24] Too many open files`. It appears that every time a new `asyncua.sync.Client` object is instantiated, we leak a few file descriptors, so over time I hit the max limit of my process. This can be recreated as follows (you will need two terminals):
- Launch a Python REPL from one terminal
- From a second terminal get the PID of the Python REPL (using `ps aux` on Linux). Then run `ls -l /proc/PID/fd | wc -l` where `PID` is the PID of the Python REPL. In my case, the output of this command is 12 active file descriptors.
- From the Python REPL, run the following lines:
```python
from …
```
> Close thread loop after stopping in sync wrapper

- asyncua/server/history.py
I noticed a small bug when trying to historize an event with a `period` value not set to the default value of `None`. While `DataValue` objects store their timestamp in the `SourceTimestamp` attribute, `Event` objects instead use the `Time` attribute. It looks like there was some code for `DataValue`s that was re-used for `Event`s, and this attribute wasn't changed, causing this error:
```python
File "asyncua\server\history.py", line 152, in save_event
while len(evts) and now - evts[0].SourceTimestamp > period:
AttributeError: 'Event' object has no attribute 'SourceTimestamp'
```
This was tested by setting a short value for `period`, triggering an event, then triggering another event after the time specified in `period`, and confirming that the first …
> Fix AttributeError when historizing events

- asyncua/client/ua_client.py
I use asyncua as a client to connect with a pretty slow server (probably it's all because of hardware)
But UaClient raises TimeoutError after 10 seconds regardless a timeout it's initialized with.
So it's a simple fix of the hardcoded timeout.
> Use UASocketProtocol.timeout as default in send_request

- asyncua/common/connection.py
In https://github.com/FreeOpcUa/python-opcua/pull/915, @jonasgreen88 introduced logic to revolve security tokens whenever a channel is renewed.
In my application, I had a client that used `opcua==0.98.5` and I recently switched to `asyncua==0.8.0`. In that switch, I started seeing an influx of errors that all said `Invalid security token id {n}, expected {n+1} or {0}`. In each case, the received token was always one less than the expected token.
After looking through the change where this was introduced, it seems like whenever the tokens were revolved, [the previous token was removed](https://github.com/FreeOpcUa/opcua-asyncio/compare/master...chrisjbremner:fix_revolve?expand=1#diff-b15c66d6385a64ef5957e8a8e40e354bL280), so that if you then received an "old" token after revolving, this …
> Don't remove previous security token when revolving tokens

- asyncua/common/structures.py
Fixed comparison with literal. Comparison with a literal (str) should always be "!=" and not "is not".
> Update structures.py - fix literal Comparison.

- asyncua/client/client.py
- asyncua/client/ua_client.py
With the current implementation, the client crashes when disconnecting while requests are awaiting their response. From the logs:
Request is sent:
```
2020-03-11 12:55:56.629 Thread-1 - asyncua.client.ua_client.UASocketProtocol - _send_request :112 - DEBUG - Sending: PublishRequest(TypeId:FourByteNodeId(i=826), RequestHeader:RequestHeader(AuthenticationToken:NumericNodeId(i=30607522), Timestamp:2020-03-11 11:55:56.629308, RequestHandle:15, ReturnDiagnostics:0, AuditEntryId:None, TimeoutHint:0, AdditionalHeader:ExtensionObject(TypeId:TwoByteNodeId(i=0), Encoding:0, None bytes)), Parameters:PublishParameters(SubscriptionAcknowledgements:[SubscriptionAcknowledgement(SubscriptionId:83, SequenceNumber:8)]))
```
A disconnect starts:
```
2020-03-11 12:55:56.655 Thread-1 - asyncua.client.client - …
```
> Fix exception when disconnecting while not all Requests were processed.

- asyncua/common/structures.py
This fixes the first problem described in https://github.com/FreeOpcUa/opcua-asyncio/issues/160#issuecomment-622985985
As stated on https://lxml.de/FAQ.html:
> First of all, XML is explicitly defined as a stream of bytes. It's not Unicode text. Take a look at the XML specification, it's all about byte sequences and how to map them to text and structure. That leads to rule number one: do not decode your XML data yourself. That's a part of the work of an XML parser, and it does it very well. Just pass it your data as a plain byte stream, it will always do the right thing, by specification.
> Fix exception raised by `lxml.objectify.fromstring`

- asyncua/common/structures.py
This fixes the second problem described in https://github.com/FreeOpcUa/opcua-asyncio/issues/160#issuecomment-622985985
> Fix bad Python identifiers ending in generated code

- asyncua/common/node.py
This allows for a workaround  for writing (relates to #711) to allow clients to write partial arrays.
I think this seems like a reasonable incremental addition but I am not sure if there is something I am missing here... in any case it does with with the OPC servers I have tested with.
> Add indexrange kwarg to Node.set_attribute

- asyncua/server/uaprocessor.py
- examples/server-minimal.py
I made the mistake earlier thinking that GetEndpoints should be only available to authenticated users. However clients such as UAExpert do a GetEndpoints before authenticating. I think therefore GetEndpoint is necessary to be allowed to unauthenticated users.
> add ability to find endpoints for unauthenticated user

- asyncua/client/ua_client.py
Fixes #241 . Simple `try/catch` block that will raise `ConnectionError` in `send_request` if connection was lost
> Raise ConnectionError in send_request if state is not OPEN

- asyncua/client/client.py
make the detailed policy ID match the signature algorithm and its other implications (leftover from the previous commit on FreeOpcUa#137).
> Authentication Certificate Policy ID

- asyncua/tools.py
- tests/conftest.py
- tests/test_tools.py
This commit adds the following:
* A server fixture which runs in a dedicated thread to handle OPC-UA requests properly (existing server fixture just accept TCP connections but can't handle hello since they are not running).
* We then use it to enhance the CLI tests and set more consistent exit codes across the cli (following the comment on #283).
* Fix the ```uaserver``` cli tool, its event_loop was stuck in non-async sleep preventing it from accepting requests.
> [ Cli tools ] Fix uaserver and tests

- asyncua/client/client.py
- asyncua/crypto/uacrypto.py
- examples/client-with-encryption.py
- tests/test_crypto_connect.py
- tests/test_permissions.py
This commit contains the following changes:
* Allow a client to specify the extension of its certificate, while keeping retro compatibility with the ```set_security_string``` API, ex:
```
In [3]: import sys; sys.path.insert(0, "/home/zuzud/github/opcua-asyncio")
...: import asyncua
...: from asyncua.crypto.uacrypto import CertProperties
...: from asyncua.crypto import security_policies
...: from asyncua.ua import MessageSecurityMode
...: URL="opc.tcp://127.0.0.1:4901/OPCUA"
...: client = asyncua.Client(url=URL)
...: user_cert = "/tmp/client-cert/testA.cert"
...: user_key = "/tmp/client-cert/testA.key"
...: security_policy = getattr(security_policies, "SecurityPolicyBasic256Sha256")
...: security_mode = getattr(MessageSecurityMode, "SignAndEncrypt")
...: await …
```
> [ Certificate ] More flexibility with certificate extensions

- asyncua/common/connection.py
- asyncua/server/uaprocessor.py
Same fix for the same problem as presented for the non-async version of the project.
Issue is discussed here: https://github.com/FreeOpcUa/python-opcua/issues/926
Corresponding PR: https://github.com/FreeOpcUa/python-opcua/pull/1135
> Fix for secure-channel-renewal bug.

- asyncua/common/methods.py
Fixes #293.
OutputArguments can possibly come back as a null array, in which case asyncua unpacks as None.
> Add None check before iteration

- asyncua/common/manage_nodes.py
The origin node is already added at the end of _add_childs.
The sequence is important because otherwise we get a BadNodeIdUnknown.
> fix delete nodes

- asyncua/crypto/uacrypto.py
This has apparently been mistakenly removed [by this commit](https://github.com/FreeOpcUa/opcua-asyncio/commit/234008be689901ba2f9d32606944474a61f84801#diff-0ccb06a6a30b67aafbe098c395870604R4) and is still required by the [security_policies](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/crypto/security_policies.py#L287).
Related issue found: #195
Before patch:
```
In [2]: from asyncua.crypto import uacrypto
In [3]: raise uacrypto.InvalidSignature
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-93aef37181e3> in <module>
----> 1 raise uacrypto.InvalidSignature
AttributeError: module 'asyncua.crypto.uacrypto' has no attribute 'InvalidSignature'
```
After: …
> [ UaCrypto ] missing InvalidSignature import

- asyncua/client/client.py
- asyncua/crypto/uacrypto.py
String are immutable, therefore the password is never encoded when it's a string and throws this error:
```
...../cryptography/hazmat/backends/openssl/backend.py in _load_key(self, openssl_read_func, convert_func, data, password)
1284         userdata = self._ffi.new("CRYPTOGRAPHY_PASSWORD_DATA *")
1285         if password is not None:
-> 1286             utils._check_byteslike("password", password)
1287             password_ptr = self._ffi.from_buffer(password)
1288             userdata.password = password_ptr
...../cryptography/utils.py in _check_byteslike(name, value)
36         memoryview(value)
37     except TypeError:
---> 38         raise TypeError("{} must be bytes-like".format(name))
39
40
TypeError: password must be bytes-like
```
This patch fixes this as well as some typing …
> [ Security ] Password encoding bug and typing adjustement

- asyncua/client/client.py
When disconnecting a client, we cancel the uaclient [publish_task](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/client/ua_client.py#L463) (done via [close_session](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/client/ua_client.py#L315-L319)). Failing at doing this can prevent a proper client reconnection since a ```publish_task``` will still be running, and could be hanging on a previous request that has never completed (i.e network issue) because Yes, there's no timeout for requests coming from the [publish_loop](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/client/ua_client.py#L505) (details about ```asyncio.wait_for(.., timeout=0)``` in #163).
When disconnecting an unhealthy client, there'a time window during which waiting on the …
> [fix] Always call ua_client.close_session on disconnect

- .travis.yml
- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/common/shortcuts.py
- asyncua/common/subscription.py
- dev_requirements.txt
- setup.py
- tests/conftest.py
- tests/test_subscriptions.py
Few updates to be able to change the mode (hot/stand-by) of the HaClient underlying connections :
- Ability to specify the publishing mode at subscription creation (enabled/disabled).
- Subscription methods to change the publishing and monitoring mode of an existing subscription.
- Add a timeout on client's connect for the connection to fail if the server can't handle it.
- Client shortcut for the service_level.
See #314 for context.
> [HaClient] subscription and client prerequisites

- asyncua/server/server.py
- tests/test_server.py
In cases where we either
- call `unregister_to_discovery()` while keeping the server running, or
- call `stop()` while keeping to drive the event loop,
we run into exceptions as the callback scheduled for automatic renewal (`_schedule_renew_registration`) keeps being executed.
This PR introduces explicit cancellation of callbacks created when scheduling the next renewal.
The callbacks are cancelled either when the server is stopped altogether or when the last entry in `_discovery_clients` is disconnected.
In addition, `unregister_to_discovery()` will now remove the entry from `_discovery_clients` so they're not used in `_renew_registration()` after having been disconnected.
Finally, I changed `unregister_to_discovery()` to a coroutine as otherwise the affected client's `disconnect()` …
> Explicitly cancel automatic discovery renewal

- tests/test_xml.py
Tests run, perhaps of #130 
Mentioned in #334
> Remove pytest.mark.skip from test_xml_method

- asyncua/server/event_generator.py
if im trying to send an event like 
```
evgen = await self._server.get_event_generator()
...
evgen.event.Message = None
await evgen.trigger()
```
I got an error like 
```ValueError: A LocalizedText object takes a string as argument "text", not a <class 'coroutine'>, <coroutine object Node.read_browse_name at 0x7f1dae170340>```
It seems to come from this code which likely hasnt been hit since the port from sync to async :)
> fix bug when sending event with no message

- asyncua/server/internal_server.py
- asyncua/server/internal_session.py
- asyncua/server/server.py
- asyncua/ua/uaprotocol_hand.py
Hello,
I noticed two bugs in UserManager and PermissionRuleSet handling:
1. the user-defined PermissionRuleset is now propagated and used also into the server endpoint with NoSecurity; without this fix a valid user has full acess to the server if uses an unencrypted connection;
2. a clear password is now passed to the user-defined UserManager.get_user when using a Basic256Sha256SignAndEncrypt endpoint.
> User manager and permission ruleset fix

- examples/client_to_uanet_alarm_conditions.py
Hi all,
great project, great codebase. Was a lot of fun to explore.
Complete client alarms and conditions example for usage with OPCFoundation UA-.NETStandard-Samples Quickstart AlarmConditionServer.
https://github.com/OPCFoundation/UA-.NETStandard-Samples
Hope that helps everyone struggling to consume alarms and conditions.
Most tricky part with Alarms and Conditions is on how to get the ConditionId. This is described at the bottom of that link:
https://reference.opcfoundation.org/v104/Core/docs/Part9/5.5.2/
To avoid the hassle for everyone to add an extra separate SimpleAttributeOperand when consuming Alarms and Conditions, I think you should think about adding something like subscription.subscribe_conditions or event.get_condition_filter_from_event_type.
Another pull request will …
> Complete client alarms and conditions example

- asyncua/tools.py
Those missing await prevent the server from loading the certificates via CLI.
```
$ ./uaserver --certificate ../examples/certificate-example.der --private_key ../examples/private-key-example.pem -v DEBUG
/home/prigentj/github/opcua-asyncio/tools/../asyncua/tools.py:561: RuntimeWarning: coroutine 'Server.load_certificate' was never awaited
server.load_certificate(args.certificate)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/prigentj/github/opcua-asyncio/tools/../asyncua/tools.py:563: RuntimeWarning: coroutine 'Server.load_private_key' was never awaited
server.load_private_key(args.private_key)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
> [uatools] Missing await to load certificates

- asyncua/client/ha/ha_client.py
- tests/test_ha_client.py
This variable is used to trace server disconnections and renew any underlying subscription/monitored items when this occurs.
Consequently, those urls have to be unique to prevent some memory-leak type of issue (i.e: Reconciliator is disabled or running slower than the Keepalive checks).
> [HaClient] url_to_reset from list to set

- asyncua/common/subscription.py
- examples/client_to_uanet_alarm_conditions.py
**Current solution for normal events:**
The current solution for subscribing to events is great. Setting the event-filter is optional. If not set, an event-filter containing all properties and variables, is auto-generated. The client coder does not need to have knowledge about the complex filter system. If he has, he can go fancy as well.
**Issue with the condition events:**
In a similar way that should be the case for an alarms/conditions client as well. But for subscribing to condition-events an extra operand in the select clause of the event filter is necessary (like in example _client_to_uanet_alarm_conditions_). Each client does need to add the same code, does need to cope with the filters, and just needs to realize that this has to be done. 
So it should be autogenerated as well. …
> Auto generate client event filter for Alarms and Conditions

- asyncua/client/client.py
- asyncua/client/ha/ha_client.py
- tests/test_ha_client.py
- tests/test_subscriptions.py
When a session has a short session timeout, the secure_channel is renewed at 75% of its lifetime. While this is convenient to keep the session alive, the encryption operations involved behind the scenes can be expensive, especially on hardware with limited resources (i.e: OPC-UA server embedded on PLC module).
The suggestion here is to give back more control to the secure channel timeout parameter, and to instead rely on the subscription keepalive mechanism to avoid timing out when subscriptions are inactive.
There's still the rare use-case when there's no subscription at all (client is connected but idling without subscriptions). In this situation, the user has to specifically set a secure_channel_timeout < session_timeout, or alternatively, use an external keepalive mechanism like the …
> [Session keepalive] Use sub keepalive instead of secure_channel 

- asyncua/common/events.py
Method call fails because a method with that name does not exist any more. Happened when taking over the older code from the initial alarms and conditions development pr.
Interestingly, no Unit Test is catching that error. So no test is reaching that code. Next thing would be a new unit test.
> Fix failing method call in CustomEvent creation

- asyncua/common/events.py
- tests/test_server.py
- tests/test_subscriptions.py
Fixes an oversight in refactoring. Creating Events for a special EventFilter with SimpleAttributeOperand including AttributeId.NodeId does fail.
The PR also adds test cases for that case and PR #455.
> Fix create events with special EventFilter and add tests

- asyncua/server/address_space.py
If on the server side only the StatusCode is changed, the clients are not informed. It only works if at the same time there is a change to the value as well. This is incorrect behavior. You should be able to set for example status code BadWaitingForInitialData without changing the value.
I think I ran into the same issue as mentioned here:
https://github.com/FreeOpcUa/python-opcua/issues/375
I extended the check for also checking the StatusCode. In fact I think even more has to be changed, but this is most important.
A client needs to be informed when:
- The value changes OR
- The status code changes OR
- One of the timestamps changes
When subscribing, the client can decide whether he wants to be informed on value, statuscode or timestamp change via the DataChangeFilter. See:
- …
> Fix no client callback on StatusCode change

- asyncua/common/structures.py
- asyncua/common/structures104.py
Clean up invalid variable names in auto generation of Enums.
I encountered servers which have white spaces in enum types and invalid characters in enum values.
The optimization in "clean_name" doubles the performance, since 99% of names are valid. I tested the performance.
> Also clean names for generated Enums

- asyncua/client/client.py
- tests/test_subscriptions.py
When RequestedPublishingInterval isn't provided, calculating the RequestedMaxKeepAliveCount raises a ZeroDivisionError.
Therefore, let's calculate RequestedMaxKeepAliveCount with a conservative PublishInterval value of 1000ms when this occurs.
Worth noting our server doesn't revise the PublishInterval value, hence will not start the publication with a value of 0.
https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/server/internal_subscription.py#L50-L51
Fixes #490
> [Fix ZeroDivisionError] RequestedMaxKeepAliveCount

- asyncua/common/xmlimporter.py
From https://reference.opcfoundation.org/v104/Core/docs/Part3/5.5.3/ :
> Organizes References can be used in any combination with HasChild References (HasComponent, HasProperty, etc.; see 7.5) and do not prevent loops. Thus, they can be used to span multiple hierarchies.
This should fix the problem, if you use both.
> Remoce organisez reference check for parentnode check

- asyncua/server/address_space.py
Added the feature discussed here:
- https://github.com/FreeOpcUa/python-opcua/issues/685
- https://github.com/FreeOpcUa/python-opcua/issues/850
- https://github.com/FreeOpcUa/python-opcua/issues/1192
I read, many wonder why the ServerTimestamp is necessary. Yes, it is necessary and equally important as the SourceTimestamp.
Why?
On simple systems the ServerTimestamp is more or less the same than the SourceTimestamp. But on more complex systems with several signal sources on different PCs or Controls it is a different topic. In the past often nobody cared about setting the correct timezone on different controls. As long as the clock showed the right time, everyone was fine. Another issue is time synchronization between the different PCs or controls. Sometimes that is not implemented at all. …
> Auto set ServerTimestamp if value is written

- asyncua/server/address_space.py
This reverts commit 0a1cce0783d93493515ff92e55952e63909fc834.
#461 causes connection problems. See #520
> Revert "Auto set ServerTimestamp if value is written"

- asyncua/client/ua_client.py
Having run into 
```
2021-04-08 14:55:44.939 WARNING  asyncua.client.ua_client.UASocketProtocol: ServiceFault from server received  in response to CreateMonitoredItemsRequest
```
and used Wireshark to check for details, I thought it might be useful to have the response code, too.
```
2021-04-08 14:55:44.939 WARNING  asyncua.client.ua_client.UASocketProtocol: ServiceFault (BadTooManyOperations) from server received  in response to CreateMonitoredItemsRequest
```
> add service result code to log

- asyncua/common/node.py
Fixes #562 Node.read_attribute doesn't support IndexRange
> read_atribute now has indexrange argument

- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/common/subscription.py
- asyncua/common/ua_utils.py
- tests/test_subscriptions.py
- tests/test_uautils.py
As discussed in #557, the MaxKeepAliveCount has to be adjusted once the server replies with a different `RevisedPublishingInterval` value. 
This change adds the methods to update the parameters of existing subscriptions. Hence, we can capture the `CreateSubscriptionResult`, re-calculate the `MaxKeepAliveCount` when needed and update the sub accordingly.
Let's set a PublishInterval of 1ms for a server which only supports 100ms and above, then check that the `MaxKeepAliveCount` value is recalculated and the subscription is modified:
```
2021-06-02 14:19:47,596 - asyncua.client.ua_client.UaClient - DEBUG - create_subscription
2021-06-02 14:19:47,596 - asyncua.client.ua_client.UASocketProtocol - DEBUG - Sending: CreateSubscriptionRequest(TypeId=FourByteNodeId(Identifier=787, NamespaceIndex=0, …
```
> [Subscription creation] adjust MaxKeepAliveCount based on RevisedPublishingInterval

- asyncua/ua/uaprotocol_auto.py
- schemas/generate_protocol_python.py
We broke UTC timestamp with #496 which means clients in a different TZ than the server aren't able to connect anymore. See the stack trace:
```
BadInvalidTimestamp                       Traceback (most recent call last)
<ipython-input-1-7c6bfb3082fd> in <module>
33         # We create a Client Subscription.
---> 34         subscription = await c.create_subscription(1000, handler)
35         #nodes = [
~/github/opcua-asyncio/asyncua/client/client.py in create_subscription(self, period, handler, publishing)
554         subscription = Subscription(self.uaclient, params, handler)
--> 555         await subscription.init()
556         return subscription
~/github/opcua-asyncio/asyncua/common/subscription.py in init(self)
86     async def init(self):
---> 87         response = await …
```
> [Fix] Revert to UTC for request header

- asyncua/tools.py
The populate option was broken since most of the calls were missing `await`.
Server
```
[(fix_tools)]> ./uaserver -p
DEBUG:asyncio:Using selector: EpollSelector
INFO:root:No user manager specified. Using default permissive manager instead.
INFO:asyncua.server.internal_session:Created internal session Internal
INFO:asyncua.server.address_space:add_node: while adding node NumericNodeId(Identifier=15957, NamespaceIndex=0, NodeIdType=<NodeIdType.Numeric: 2>), requested parent node NumericNodeId(Identifier=11715, NamespaceIndex=0, NodeIdType=<NodeIdType.Numeric: 2>) does not exists
INFO:asyncua.server.address_space:add_node: while adding node NumericNodeId(Identifier=15958, NamespaceIndex=0, NodeIdType=<NodeIdType.Numeric: 2>), requested parent node NumericNodeId(Identifier=15957, …
```
> fix tools/uaserver with populate arg

- asyncua/server/address_space.py
- tests/test_common.py
Mentioned problem in #594 .
This PR shall remove the wrong handling of browsenames and making a step in the right direction.
This is only one point from 594 (the easiest one). Since the other two points (InstanceDeclaration and TypeDefinition) are more complex, they shall be introduced in a seperate PR.
> Fix browsename uniqueness for properties

- asyncua/server/internal_subscription.py
- asyncua/server/subscription_service.py
When I try to delete subscriptions, I run into `CancelledError` as shown below. I believe this is because we are trying to await the subscription task immediately after cancelling it, which raises the error. When `asyncio.gather` is run the error crashes the server.
```python
File "...\asyncua\server\uaprocessor.py", line 126, in process_message
return await self._process_message(typeid, requesthdr, seqhdr, body)
File "...\asyncua\server\uaprocessor.py", line 190, in _process_message
await self.session.close_session(deletesubs)
File "...\asyncua\server\internal_session.py", line 74, in close_session
await self.delete_subscriptions(self.subscriptions)
File "...\asyncua\server\internal_session.py", line 180, in delete_subscriptions
return await …
```
> Ignore errors during subscription deletion

- asyncua/common/callback.py
- asyncua/server/internal_session.py
Added a field to ServerItemCallback class used by CallbackManager to distinguish events triggered by server itself from one from external clients.
> External argument to server callbacks

- asyncua/tools.py
The OPC UA specification does not forbid that a server does not offer DiscoveryUrls. This can lead to a crash when calling the function application_to_strings().
Check DiscoveryUrls for None or empty before iterating to avoid the crash described in #1127 (project python-opcua).
> Fix crash if server does not provide DiscoveryUrls

- asyncua/client/client.py
- tests/test_crypto_connect.py
- tests/test_ha_client.py
When a client wants to connect with encryption and doesn't provide the server certificate, it first catches the server cert by listing the [endpoints available](https://github.com/FreeOpcUa/opcua-asyncio/blob/fc09e423c7f3e49783b0788ad0933fd836175c15/asyncua/client/client.py#L148). Since the initial client creation has an empty `security_policy`, the SecureChannel required for this listing is unencrypted/unsigned (See [OPC-UA 6.7.4](https://reference.opcfoundation.org/v104/Core/docs/Part6/6.7.4/))
However when the same client instance reconnects, it re-uses the existing security policy (which now contains the server certificate) and creates an encrypted/signed [SecureChannel]((https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/client/client.py#L289)) for all subsequent …
> [Sec_Policy] Handle server certificate renewal gracefully

- asyncua/common/ua_utils.py
- asyncua/ua/ua_binary.py
- asyncua/ua/uaprotocol_auto.py
- schemas/generate_model_from_nodeset.py
- schemas/generate_protocol_python.py
Support OptionSets from Part5 7.17 like UadpNetworkMessageContentMask. They were generate as Enumerations before.  In nodesets they are Enumerations with attribut "IsOptionSet" = True.
Example from DataSetFieldContentMask:
```
<UADataType NodeId="i=15583" BrowseName="DataSetFieldContentMask">
<DisplayName>DataSetFieldContentMask</DisplayName>
<Documentation>https://reference.opcfoundation.org/v104/Core/docs/Part14/6.2.3/#6.2.3.2</Documentation>
<References>
<Reference ReferenceType="HasProperty">i=15584</Reference>
<Reference ReferenceType="HasSubtype" IsForward="false">i=7</Reference>
</References>
<Definition Name="DataSetFieldContentMask" IsOptionSet="true">
<Field Name="StatusCode" Value="0" />
<Field Name="SourceTimestamp" Value="1" />
<Field Name="ServerTimestamp" Value="2" /> …
```
> Support OptionSets

- asyncua/tools.py
Running uals recursively with -l option gives RuntimeWarning:
```
$ uals -d 3 -l
Browsing node i=84 at opc.tcp://localhost:4840
DisplayName                    NodeId                    BrowseName                DataType   Timestamp                      Value
File ".../opcua-asyncio/tools/uals", line 11, in <module>
uals()
File ".../opcua-asyncio/asyncua/tools.py", line 342, in uals
asyncio.run(_uals())
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File ".../opcua-asyncio/asyncua/tools.py", line 368, in _uals
await _lsprint_long(node, args.depth - 1)
File ".../opcua-asyncio/asyncua/tools.py", line …
```
> Add missing await in uals -l -d

- asyncua/client/ua_file_transfer.py
- examples/client-ua-file-transfer.py
- examples/client_ua_file_transfer.py
Closes #695 
This PR contains all FileSystem functions marked as mandatory in the OPC UA Spec.
See:
OPC 10000-5: OPC Unified Architecture V1.04
Part 5: Information Model - Annex C (normative) File Transfer
The FileType functionality "./client/ua_file_system.py - class UaFile" is not compatible to the "old" implementation in "./client/ua_file.py".
I decided to do this because the build-in python open-mode differs significantly from OPC UA open-mode. The open-mode written in the OPC UA spec. does not map unambiguously to the char-based open-mode in python build-in.
Maybe the old ua_file.py should be removed. I think that is justifiable, because ua_file.py::UaFile() was incomplete and buggy. For example, it reacted differently when used in the context manager or without. Switching to the new …
> Add low-level file system functionality

- asyncua/ua/ua_binary.py
- asyncua/ua/uatypes.py
This pull request applies the same changes as https://github.com/FreeOpcUa/opcua-asyncio/pull/700 to the deserialization code, with similar speedups measured in my tests. As before, most of the deserialization time is now spent creating the objects, as opposed to introspecting the object types.
I also changed the timestamp object serialization function. The new function is ~7 times faster than the old one, resulting in a further 1.5x speedup in my serialization test.
> 3x performance improvement in deserialization

- asyncua/server/subscription_service.py
In https://github.com/FreeOpcUa/opcua-asyncio/pull/648, I added logic to ignore and log errors when deleting subscriptions. In that change, I made a mistake in assuming that `asyncio.gather` would only return a list of exceptions when using `return_exceptions`, when in reality it returns a list containing either the return value or an `Exception` object for each coroutine. This meant that when all the subscriptions were successfully deleted, it would return a list of `None` objects, which then led to the warning message being logged with an empty `exc_info`. In this PR, I added a check to determine if any of the return values from `asyncio.gather` were `Exception`s, and then only log the warning if the subscription deletion actually failed.
> Avoid false warning when deleting subscription

- asyncua/client/ha/__init__.py
- setup.py
- tests/test_ha_client.py
The HaClient is missing from the PyPi package
```
[/tmp]> curl https://codeload.github.com/FreeOpcUa/opcua-asyncio/tar.gz/refs/tags/v0.9.91 -s -o v0.9.91.tar.gz
[/tmp]> tar xvf v0.9.91.tar.gz > /dev/null 2>&1
[/tmp]> cd opcua-asyncio-0.9.91/
[/tmp/opcua-asyncio-0.9.91]> python setup.py install > /dev/null 2>&1
[/tmp/opcua-asyncio-0.9.91]> find build/ -type f |grep -i ha
build//lib/tests/test_ha_client.py
build//lib/asyncua/ua/uaprotocol_hand.py
```
The build rules only look for the packages via `find_packages` in setup.py, making the `ha` subdirectory a package fixes it:
```
[/tmp/opcua-asyncio-0.9.91]> rm -rf build/
[/tmp/opcua-asyncio-0.9.91]> cat asyncua/client/ha/__init__.py
"""
Pure Python OPC-UA library
"""
from .ha_client import HaClient, HaMode, HaSecurityConfig, …
```
> [PyPi] Missing files

- asyncua/client/client.py
- asyncua/client/ua_client.py
- tests/test_connections.py
Follow-up of #711 
Make sure calling disconnect is safe when connection isn't established or half-established (i.e: protocol/transport exist but session is not ready).
Call to disconnect is safe when there's no existing connection
```
> python -m IPython
Python 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
In [1]: import sys; sys.path.insert(0, "~/Documents/github/opcua-asyncio"); import asyncua; c = asyncua.Client(url="opc.tcp://localhost:4840",timeout=10
...: );
In [2]: await c.disconnect()
close_session but connection wasn't established
close_secure_channel was called but connection is closed
In [3]:
```
Ensure that call to disconnect is safe when there's no session established.
To simulate this, I add delay to the server internal_session on session …
> [Safe Client disconnect]

- asyncua/common/ua_utils.py
- asyncua/common/xmlimporter.py
- asyncua/common/xmlparser.py
This is a fix I made concerning:
https://github.com/FreeOpcUa/python-opcua/issues/1368
It allows the xmlimporter to use customn data types that are imported in the same sequence when being used in variables. This was necessary for the I40AAS companion spec found here:
https://github.com/OPCFoundation/UA-Nodeset/tree/v1.04/I4AAS
> Changes to xmlimporter to load customn data types when needed

- asyncua/client/ha/ha_client.py
- asyncua/client/ha/reconciliator.py
With py3.10, high level asyncio API can't specify the event_loop argument anymore.
Consequently, when using thread dedicated to run the `event_loop`, we now need to instantiate objects like asyncio.Lock within the thread. However, the event loop can't be running before creating these objects as `loop.run_for_ever()` must be the background running thread process. Therefore, having`get_running_loop()` calls in object constructors (like HaClient) is an antipattern when used through executors.
Before
```
In [15]: def get_t():
...:     loop = asyncio.new_event_loop()
...:     t = T()
...:     loop.run_for_ever()
In [16]: class T:
...:     def __init__(self, loop):
...:         asyncio.set_event_loop(loop)
...:         asyncio.get_running_loop()
...:         self.l = asyncio.Lock()
...: …
```
>  [HaClient] Allow init from executor

- asyncua/common/structures104.py
Parsing custom enumerations no longer logs an error in case of success. Same as in parsing of custom structures.
> Fix misplaced error message

- asyncua/common/events.py
- asyncua/common/subscription.py
- asyncua/crypto/uacrypto.py
This pull request should contain a fix for issue #752. I am really not sure, if I should also add additional `bytes` calls to the other encryption and decryption functions of `uacrypto.py`? 
At least for my command line tool – based on `opcua-asyncio` – the additional `bytes` call did not introduce problems on my other testing platform (macOS).
> Windows: Crypto Type Error Fix

- asyncua/server/address_space.py
- asyncua/ua/uaprotocol_auto.py
- asyncua/ua/uatypes.py
Hi everybody,
I started with issue #594 but got stuck in the code because I had to double check each call to understand parameters and whats going on. I started to add some type hinting for each discovery and at the end I was adding type hinting instead of fixing the issue.
Please let me know, if your are interested in code quality improvements. - Feel free to stop it here. But for me, things are getting much better now and this was only the start of this journey.. :-)
While swimming through the code i got some points (see added Fixme/ question comments) I would like to ask the community.
1. The access to _nodes look ugly and complicated to me. Is there a reason why we do it this way?
2. ua.StatusCode is typed as UInt32 but the constructor is called with int. Is this UInt32 data type …
> Introduce type hinting into address_space.py for online discussion

- asyncua/common/utils.py
__bytes__ on the Buffer object is sometimes returning a bytearray instead of bytes.
File "C:\Users\ddeason\PycharmProjects\opcua_test\venv\lib\site-packages\asyncua\client\ua_client.py", line 88, in _process_received_data
data = bytes(buf)
TypeError: __bytes__ returned non-bytes (type bytearray)
> __bytes__ on the Buffer returning non-bytes

- asyncua/ua/ua_binary.py
The serializer for the Encoding field is hardcoded at the moment to "Byte". This prevented the use of Optionals and Unions as the OPCUA v104 specification expects it to be UInt32 in both cases, even tough the field type of the Encoding field was set correctly to UInt32 (see https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.7/ and https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.8/). This can simply be fixed by using the field serializer also for the encoding field and should still work correctly for Encoding field with type "Byte".
> fix hardcoded field serializer for Encoding field

- asyncua/ua/uatypes.py
This fixes a bug I discovered.
Steps to reproduce:
1) run the script below
import asyncio
from asyncua import ua, Server
async def main():
server = Server()
await server.init()
server.set_endpoint('opc.tcp://0.0.0.0:4840/')
uri = 'http://bugs.freeopcua.github.io'
idx = await server.register_namespace(uri)
myobj = await server.nodes.objects.add_object(idx, 'MyObject')
await myobj.add_variable(idx, 'SByte', ua.uatypes.SByte(-128))  # TODO: raises an exception
await myobj.add_variable(idx, 'Byte', ua.uatypes.Byte(255))  # TODO: the value is not an integer but a byte-string
await myobj.add_variable(idx, 'Int16', ua.uatypes.Int16(-32768))
await myobj.add_variable(idx, 'UInt16', ua.uatypes.UInt16(65535))
async with server:
while True:
await asyncio.sleep(1)
if __name__ == '__main__': …
> asyncua.ua.uatypes.SByte and asyncua.ua.uatypes.Byte inherit from int instead of bytes

- asyncua/server/address_space.py
Similar to https://github.com/FreeOpcUa/opcua-asyncio/pull/102
> Import ABC from collections.abc for Python 3.10 compatibility.

- asyncua/__init__.py
- setup.py
Make the package version available as `asyncua.__version__` at runtime.
> Make package version available at runtime

- asyncua/common/instantiate_util.py
#842 broke the instantiate function for Methods, because they don't have the attribute IsAbstract.
> allow instantiation of Methods

- .github/workflows/python-package.yml
- asyncua/client/client.py
- asyncua/client/ha/ha_client.py
- asyncua/client/ha/reconciliator.py
- asyncua/client/ha/virtual_subscription.py
- asyncua/common/connection.py
- asyncua/common/structures104.py
- asyncua/common/subscription.py
- asyncua/common/xmlimporter.py
- asyncua/server/address_space.py
- asyncua/server/history.py
- asyncua/server/internal_server.py
- asyncua/server/server.py
- asyncua/tools.py
- asyncua/ua/uaprotocol_auto.py
- asyncua/ua/uatypes.py
- setup.cfg
- mirror change from mypy
- ignore mypy errors
- better to fix issues step by step
```python
from sortedcontainers import SortedDict  # type: ignore
ProductUri: String = None  # type: ignore
disable_error_code = misc
class SubHandler(SubHandler):  # type: ignore
class Union:  # type: ignore
from IPython import embed  # type: ignore
disable_error_code = arg-type
disable_error_code = attr-defined
disable_error_code = var-annotated
disable_error_code = attr-defined
disable_error_code = union-attr
def _to_migrated_nodeid(self, nodeid: Union[ua.NodeId, None, str]) -> Union[ua.NodeId, ua.QualifiedName]:
disable_error_code = override
identifier_list = sorted(  # type: ignore
return await self._subscribe(sourcenode, ua.AttributeIds.EventNotifier, evfilter, queuesize=queuesize)  # type: ignore …
```
> enable mypy

- .gitignore
- README.md
- asyncua/common/node.py
- asyncua/ua/uatypes.py
- tests/test_client.py
- tests/test_subscriptions.py
* Previously a client could not read values with bad status.
* This functionality can be toggled on and off.
* Added tests.
Fixes #856
> fix: read_attribute can optional not raise an exception

- asyncua/common/structures104.py
- asyncua/ua/uatypes.py
- tests/test_common.py
- tests/test_xml.py
- Load union subtypes, they were ignored before.
- Load alias for basic datatypes, for example in #899 where WORD is UInt16
- Added a retries up to 10 times to resolve all custom structes
test the new code against opc.tcp://opcuademo.sterfive.com:26543
with multiple companion specs loaded.
Need to implement some basic testing
> rework struct1_04 resolution

- asyncua/common/events.py
- tests/test_subscriptions.py
If a EventType has a object as child, add it's variables and properties to the eventfilter. Also handles variables that contain nested variables or objects.
Fixes #905
> EventFilter: handle objects in EventTypes

- asyncua/client/client.py
- asyncua/common/xmlexporter.py
- asyncua/server/server.py
- tests/test_xml.py
Allow disable of exporting values from variables.
Normally you don't need the values in the nodeset. As side effect it reduces the time need to export a nodeset and the xml size.
Because of the the incompleteness of the xml encoding I would disable the variable export per default.
> XMLExport: make export values optional

- asyncua/client/client.py
- asyncua/client/ua_client.py
Now you can call activate_session() without arguments without discarding a certificate previously set with load_client_certificate().
> Fixes #929 activate_session(without arguments) discards previously set certificate.

- .vscode/settings.json
- asyncua/common/events.py
- asyncua/common/node.py
- asyncua/common/structures104.py
Reduced network transactions:
- instead of 3 browse request (get_properties, get_variables, get_objects) use 1.
- no read_browse_name 
- refactored logic into 1 function
The addition to Node is needed because in events.py you can't import node because of circular dependency.
> speed up eventfilter creation

- asyncua/common/xmlexporter.py
instead of Node.to_string 
_node_to_string correctly maps namespaces idxs
> Use XmlExporter _node_to_string

- asyncua/common/xmlimporter.py
- asyncua/common/xmlparser.py
- tests/test_xml.py
Add missing namepace meta if missing, to the server. Otherwise depending namespaces will fail.
See #846
> XMLImport - add namespace meta if missing in nodeset

- asyncua/sync.py
Hi,
Some methods were still missing to the sync api:
- `Server.load_certificate`
- `Server.load_private_key`
- `Server.set_security_IDs`
- `Client.get_root_node`
Some methods were also not matching the async method when looking at the parameters and default values:
- `permission_ruleset` in `set_security_policy` method
- Default value of `disable_clock` method
This PR is linked to https://github.com/FreeOpcUa/opcua-asyncio/discussions/682#discussioncomment-1441739 but it would be better to merge what is already missing and fixable and complete later the missing implementations (UaFileSync, UaDirectorySync)
Let me know if something else missing in the sync api could also be added in this PR
> Completion of the Sync api

- asyncua/common/structures104.py
- asyncua/ua/ua_binary.py
EncodingMask was the wrong datatype see: https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.7/
Fixes #994
> use correct datatype for encoding

- asyncua/common/event_objects.py
- schemas/generate_event_objects.py
Fix default value of LocalTime field in BaseEvent
The first argument to add_property sets the default value of the property on the Event. In the case of LocalTime, this should be a python TimeZoneDataType object instead of the NodeId of the TimeZoneDataType ObjectType Node.
> Fix default value of LocalTime field

- asyncua/client/client.py
- tests/test_password.py
Username and password are still urlencoded when returned from urlparse. Unquote them before use.
Strip credentials from server_url afterwards, preventing them to be sent unencrypted in e.g. send_hello.
Furl would have been a better url manipulation library, but I didn't want to add another dependency.
> Fix credentials in server_url

- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/server/uaprocessor.py
- tests/conftest.py
- tests/test_connections.py
- tests/test_crypto_connect.py
- tests/test_permissions.py
Properly close session and cancel _renew_channel_task if connect() fails in activate_session(). This avoids the need for calling disconnect() after connect() failed, leading to better call semantics.
Unfortunately, CloseSessionRequest wasn't allowed to be called in an inactivated session (it is now).
For compatibility with older asyncua servers, BadUserAccessDenied gets ignored in CloseSessionResponse.
This also cleans up some tests, which needed to call disconnect() but expected it to fail.
> Always close session

- asyncua/common/xmlparser.py
The default DataType of a struct field should be i=24 -> BaseDataType.
Found this error in Opc.Ua.Plastics.Rubber.GeneralTypes
> xmlimport change datatype field default

- asyncua/client/client.py
- asyncua/client/ua_client.py
- tests/test_connections.py
This adds a new task to pull the connection status, which will prevent a session timeout as of #977. Is also used in the next step to inform all subscriptions about a connection lose. 
Also add a hook to check if this task an `_renew_channel_loop` thrown a exception. See #974.
> [Client] Add watchdog for connection status

- asyncua/common/events.py
- asyncua/common/instantiate_util.py
- asyncua/common/ua_utils.py
- asyncua/server/address_space.py
- tests/test_common.py
Fix interpretation of IncludeSubtypes in Browse requests.
According to the spec, IncludeSubtypes indicates whether subtypes of the ReferenceType should be included in the browse. If TRUE, then instances of ReferenceType and its subtypes are returned.
The current implementation has a different interpretation: Get instances of ReferenceType and subtypes thereof. If IncludeSubtypes is FALSE, then exclude the type "HasSubtype".
The same applies to RelativePath requests.
Fixes #233.
There may be conflicts with #1017, I can rebase when it got merged.
**WARNING: This change has compatibility drawbacks, not sure how to deal with it in all cases.**
* Old client with new server (or other opcua servers):
If using add_object with type definition (or directly using instantiate), no children will get …
> Fix interpretation of IncludeSubtypes

- asyncua/common/events.py
- asyncua/common/xmlexporter.py
- asyncua/common/xmlimporter.py
- asyncua/server/address_space.py
- tests/test_common.py
This fix mostly applies to custom event or reference types, which coincidentally have the same Identifier than a predefined type with NamespaceIndex 0.
> Always take NamespaceIndex into account when comparing NodeIds

- asyncua/common/structures104.py
- asyncua/ua/ua_binary.py
- tests/test_common.py
In the conversation of #839 we found the following:
A union datatype with multiple fields that contain the same datatype wasn't possible. 
An example that didn't work in pseudo code:
```
Union{
Error: ua.UInt16
GoodString: ua.String
Good: ua.UInt16
}
```
To fix it I added a field **_union_types** that contained a list with all types in the correct order
> union allow multiple fields with the same type

- asyncua/common/structures104.py
- asyncua/common/xmlimporter.py
Fixes #1051
As of spec basedatatype should be:
<html>
<body>
baseDataType | NodeId | The NodeId of the direct supertype of the DataType. This might be the abstract Structure or the Union DataType.
-- | -- | --
</body>
</html>
In the xml importer abstract has to False as default value:
``` XML
<xs:attribute name="IsAbstract" type="xs:boolean" default="false" />
```
> correct 1.04 struct basedatatype

- asyncua/ua/uatypes.py
For completness, these datatypes are abstract! If they are used in structs, abstract types are either Variant or ExtensionObjects.
If they only contain basic types (int16, float, double..) they are Variants.
https://github.com/FreeOpcUa/opcua-client-gui/issues/87
> add Integer and UInteger types

- asyncua/client/client.py
- asyncua/client/ua_client.py
One of our tests revealed a problem with the latest 0.9.98 where if doing `close_session` followed by `create_session` no subscription updates would be received after creating a subscription. The cause seems to be that `self._closing` is not set to False when recreating a session, so the `publish_loop` won't run.
> Set _closing to False in create_session.

- asyncua/client/client.py
- asyncua/client/ua_client.py
- tests/test_connections.py
If the watchdog task gets an error all subscription handler with **status_change_notification** method will be called with BadShutdown. 
Also only prints an info message if the connection is lost.
> Client: inform all subscription handler about connection lose

- asyncua/common/xmlimporter.py
- tests/custom_ns_meta_add.xml
- tests/test_xml.py
Fix typo in in `XmlImporte._check_if_namespace_meta_information_is_add` ed which results in an exception.
In case it was required after the import to still add an ns an exception occured. On normal flow the line `_check_if_namespace_meta_information_is_added`s  with the typo isn't executed and no test was available to test the behaviour.
* Added test for `_check_if_namespace_meta_information_is_added`
* Fix the typo:
```python
obj = await self.nodes.namespaces.add_object(idx, uri, ua.ObjectIds.NamespaceMetadataType, False)
```
should be:
```python
obj = await self.server.nodes.namespaces.add_object(idx, uri, ua.ObjectIds.NamespaceMetadataType, False)
```
> Fix typo in in XmlImporte._check_if_namespace_meta_information_is_add ed which results in an exception

- asyncua/common/xmlimporter.py
- asyncua/common/xmlparser.py
The parameter/metadata MaxStringSize for string fields in structures is missing. This PR fixes that.
> added the parameter to the parser and xml importer

- asyncua/common/xmlparser.py
Attribute id 20, historizing is missing from NodeData class.
https://reference.opcfoundation.org/v104/Core/docs/Part6/A.1/
> Add missing attribute to node data

- asyncua/common/utils.py
- asyncua/common/xmlexporter.py
- asyncua/common/xmlimporter.py
- tests/test_xml.py
I have improved the export and import of extension objects to xml. Currently only tested with a b&r plc. 
While testing I found that the the following entries are missing in 'ua.object_ids.py':
```python
class ObjectIds:
ProgramDiagnostic2DataType = 15396
ObjectIdNames[15396] = 'ProgramDiagnostic2DataType'
```
I can't find how  `object_ids.py` is generated, so I could not fix it.
> improved exporting and importing extension objects to/from xml

- asyncua/server/address_space.py
- asyncua/ua/uatypes.py
- tests/test_unit.py
Previously it also did so for uncertain status code.
Fixes #1102
> Only set value to Null if status code is bad

- asyncua/common/structures.py
The Encoding Field and SwitchField are the same so we ignore SwitchField Field.
The error was triggered against non opcua-asyncio servers/clients.
Fixes #1093
> ignore SwitchField field in optionsets

- asyncua/client/client.py
The parameter is not an instance of ua.SecurityPolicy, but a subclass of ua.SecurityPolicy. This change satisfies the type-checker in PyCharm.
> Fix the policy-type-annotation in set_security

- asyncua/client/client.py
- asyncua/crypto/uacrypto.py
- asyncua/server/server.py
- tests/test_crypto_connect.py
Certificates, that are already loaded into memory as bytes, can now directly be handed over to set_security and load_certificate.
Renaming the parameter to `path_or_content` might not be that beautiful, but not too cumbersome and does the job. But I'm open for other names.
My first intention was to offer an `io`-based alternative instead of bytes, but during the implementation, `bytes` felt more natural.
> Enable usage of certificates that are already loaded into memory

- asyncua/client/ua_file.py
Currently it is possible to write a file with the low-level file services, but the comfort function in `asyncua/client/ua_file.py` is missing.
I have now added the `write()` method to `asyncua/client/ua_file.py`. This allows to write a file comfortably without using the low-level functions.
```python
async with Client(url=url) as client:
file_node = client.get_node("ns=2;s=NameOfNode")
async with UaFile(file_node, 'w') as ua_file:
with open("filename.txt", 'rb') as fd:
data = fd.read()
await ua_file.write(data) # write file
```
> UaFile: Comfort method to write file

- asyncua/server/history.py
I believe there is an off-by-one error in calculation of continuation point timestamp.
> Fix off-by-one error in continuation point calculation.

- asyncua/server/address_space.py
- asyncua/server/internal_server.py
- asyncua/server/server.py
This is a follow up on #461.
According to [7.11.4 ServerTimestamp](https://reference.opcfoundation.org/Core/Part4/7.11.4/): The serverTimestamp is used to reflect the time that the Server received a Variable value or knew it to be accurate.
I think it shouldn't be set by a client, so it gets overwritten if specified. After working with some historian systems, I came to the conclusion, that it's essential to always use the same clock for each kind of timestamp.
SourceTimestamp is only set for Value Attributes, the spec doesn't specify this for ServerTimestamp, so I assume it's ok to be set for all attributes.
> Set ServerTimestamp when attributes/values are written

- asyncua/server/internal_session.py
A malicious client can ignore BadIdentityTokenRejected (or other raised errors) and its session is still active, which means that later requests are answered by the server.
With this change, later requests are rejected with BadSessionNotActivated.
> Don't activate session for unauthorized users

- asyncua/ua/uatypes.py
- tests/test_unit.py
#1155
If a datetime is equal or before 1601-01-01 12:00AM UTC or equal or later  9999-12-31 11:59:59PM UTC return the correct values as of https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.5#_Ref400565610 .
Also removed the warning in win_epoch_to_datetime. Because the behavior is defined in the spec.
> Truncate datetime

- asyncua/server/internal_session.py
- tests/test_server.py
OPC-UA specification Part 4, 5.6.3 specifies that a Null or empty user token shall always be interpreted as anonymous. Add a test for this case and a fix to properly handle it.
I have a client that uses a Null token when connecting that is refused by the server. I don't know if the empty case would be different.
I'm not sure if the fix should remain in `internal_session.py` or move somewhere in the parser or accepted tokens, feel free to point me toward a more suitable place if needed.
> Interpret Null UserIdentityToken as Anonymous during ActivateSession

- asyncua/server/address_space.py
- tests/test_client.py
- tests/test_common.py
Prefer `None` over `ua.Null()`, otherwise a check in server code like `value.Value.Value is None` doesn't work
> Don't use ua.Null

- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/server/server.py
- asyncua/server/uaprocessor.py
- tests/test_server.py
A [Server](https://reference.opcfoundation.org/search/17?t=Server)shall establish a [SecureChannel](https://reference.opcfoundation.org/search/17?t=SecureChannel)with the [Discovery Server](https://reference.opcfoundation.org/search/17?t=Discovery%20Server)before calling this [Service](https://reference.opcfoundation.org/search/17?t=Service). The [SecureChannel](https://reference.opcfoundation.org/search/17?t=SecureChannel)is described in [5.5](https://reference.opcfoundation.org/Core/Part4/v104/docs/?r=_Ref187648579). The [Administrator](https://reference.opcfoundation.org/search/17?t=Administrator)of the [Server](https://reference.opcfoundation.org/search/17?t=Server)shall provide the [Server](https://reference.opcfoundation.org/search/17?t=Server)with an …
> fix-register-server-sessionless

- asyncua/common/xmlexporter.py
Other nodeids namespace are corrected to ``dx_in_exported_file`, only  the extensionobject typeid identifier isn't. Resulting in bad export.
Example:
```
<uax:ListOfExtensionObject>
<uax:ExtensionObject>
<uax:TypeId>
<uax:Identifier>i=296</uax:Identifier>
</uax:TypeId>
<uax:Body>
<uax:Argument>
<uax:Name>MyFiled</uax:Name>
<uax:DataType>
<uax:Identifier>ns=3;i=3003</uax:Identifier>
</uax:DataType>
```
In the case above `<uax:Identifier>ns=3;i=3003</uax:Identifier>` isn't corrected. This can be easly fixed in `XmlExporter._val_to_etree` by using the lookup table `self._addr_idx_to_xml_idx`.
> [xmlexporter] fix extensionobjects typeid indentifier missing namespace mapping to idx_in_exported_file

- asyncua/common/structures104.py
Normally nobody would ever have to use load_custom_struct, but there seem to be some typos breaking it
> Fix loading a single custom struct

- asyncua/ua/uatypes.py
- tests/test_common.py
- tests/test_unit.py
Allow bytestring nodeids with non unicode bytestring. Like 0x000F0A.
Fixes #1203, #1207
> allow non unicode bytestring nodeid

- asyncua/server/history.py
When event is saved it is added to `self._events[event.emitting_node]`, only that list is never initialized.
Append on line 170 will fail in that case.
> fix server history save event; init list before use

- asyncua/ua/ua_binary.py
Allow registration of own (de)serializer for extension objects that are not in the ua namespace. (see original TODO in code)
example:
```python
@dataclass
class YourDataType:
data_type = ua.NodeId.from_string('''ns=2;i=3007''')
Encoding: ua.UInt32 = field(default=0, repr=False, init=False, compare=False)
ID: ua.String = ua.String()
Description: Optional[ua.String] = None
ua.register_extension_object("YourDataType",
ua.NodeId.from_string( f"ns=2;i=5002"),
YourDataType,
YourDataType.data_type)
```
> allow custom (de)serializer in other namespace than ua

- asyncua/ua/uatypes.py
Most types in `ua.uatypes`, for example like `CharArray` and `Float`, are derived from a matching Python datatype.
But this isn't the case for `ua.uatypes.String`. In #609 the typedef is changed from `class String(str):` to `class String:`.
Not sure why this is done and if the original reason is still the case . If I change it back and run pytest no new errors are introduced. It even fix an existing issue in the test:
```
./tests/test_common.py::test_alias[client] Failed: [undefined]AttributeError: 'String' object has no attribute 'encode'
```
By having no str as baseclass makes use of the python typing system hard:
```python
my_string : ua.String = "" # due typing invalid
my_string : ua.String = ua.String()  # Quite unusable, return empty ua.String object
```
Fro more background …
> [ua.uatypes.String] used str as base class instead off nothing

- asyncua/common/structures104.py
- tests/test_common.py
Changes:
* Python typing friendly for numbers and strings
* Make optional basic type fields default None
> tweak default values used fields of ExtensionObject dataclasses

- asyncua/server/internal_server.py
- asyncua/server/internal_session.py
- asyncua/server/server.py
- asyncua/server/uaprocessor.py
This is especially handy when the server runs behind NAT or inside docker container, but a static EndpointUrl cannot be used because the host is multihomed.
If no EndpointUrl is specified in the request, the server first tries to use the socket address and then falls back to the statically configured EndpointUrl.
> Respect EndpointUrl request parameter in GetEndpoints, FindServers and CreateSession

- asyncua/server/monitored_item_service.py
- tests/test_subscriptions.py
deep copy monitoritem saved values, otherwise mutable value doesn't trigger a datachange.
Fixes #1239
> fix monitoritem for mutable values

- asyncua/server/monitored_item_service.py
- tests/test_subscriptions.py
Currently with  `ua.DataChangeTrigger.StatusValueTimestamp` it only triggers when the SourceTimeStamp or the StatusCodes changes. Not on value updates.
According to Part 4 7.17.2 DataChangeFilter when the trigger is `ua.DataChangeTrigger.StatusValueTimestamp` is should trigger if either StatusCode, value or SourceTimeStamp changes.
No tests where available for monitored items, test added for this situation.
> Fix `MonitoredItemServer._is_data_changed`, when as trigger `ua.DataChangeTrigger.StatusValueTimestamp` is used.

- asyncua/server/internal_session.py
- asyncua/server/internal_subscription.py
- asyncua/server/subscription_service.py
- asyncua/server/uaprocessor.py
- tests/test_subscriptions.py
PublishResults get created each PublishingInterval and queued in UaProcessor, even if no PublishRequest has been received yet.
In high load / latency situations, this leads to two issues:
a) Consuming more and more memory, because more results are getting queued than PublishRequests will arrive
a) QueueSize for monitored items doesn't really work, because each PublishingInterval, changes are already converted to PublishResults. New changes will end up in new queues, instead of old values getting discarded.
This fix now waits till a PublishRequest is available, before actually creating PublishResults.
> Fix publishing in high load situations

- asyncua/common/structures104.py
- asyncua/ua/ua_binary.py
- asyncua/ua/uatypes.py
- tests/substructs.xml
- tests/test_common.py
See end of #839. Allow Datatypes with something like this:
```Python
class X: 
x: Optional[list[int]]
```
> [Datatypes] allow optional arrays

- asyncua/crypto/uacrypto.py
application_uri is a string, but san_uri is an array of strings. The comparison will fail therefore.
> Correct certificate checks for application_uri and hostname

- asyncua/crypto/uacrypto.py
- asyncua/server/internal_server.py
When sending FindServerRequest with empty serverUris parameter ServerUris can't be looped over.
When length of the list for serverUris is -1, _create_uatype_array_deserializer will return None.
This can't be looped over.
I suggest to set params_server_uris to empty list if this happens.
> Update handling of empty server uri params

- asyncua/common/node.py
A nodeid should never be none, as instantiation of a node object will fail if the nodeid cannot be set. Properly typing nodeid helps with type checkers.
> Typing the nodeid field on a node.

- asyncua/client/client.py
- asyncua/sync.py
`read_values` is a nice and fast way to get a bunch of values in one request, but I wanted access to the `SourceTimestamp` in addition to the `Value`, which wasn't possible with this method, so I added it. If there's another way to read the values and timestamps from hundreds of nodes in one request, this isn't necessary.
> Add `read_attributes` method to `Client`

- examples/server-woodworking.py
This sample server documented how to import several nodesets in a server and how to instantiate objects with the mandatory nodes predefiend in a  nodeset. It further shows how to write and update nodes.
> Sample on instantiating objects from imported nodesets into a server

- asyncua/sync.py
This pull request enables historical data reading by synchronous client wrapper.
The pull request was created as a continuation of this [discussion](https://github.com/FreeOpcUa/opcua-asyncio/discussions/1345).
> Adding historical data reading methods to SyncNode wrapper

- asyncua/common/node.py
The description of the function FreeOpcUa / opcua-asyncio / asyncua / common / node.py / read_raw_history() declares that non-zero `numvalues` parameter should truncate the amount of historical data to receive from a server:
> Read raw history of a node
> result code from server is checked and an exception is raised in case of error
> If numvalues is > 0 and number of events in period is > numvalues
> then result will be truncated
Actually, `numvalues` parameter is practically useless and has no effect on the function behavior. The function always reads and returns full set of historical information as defined by the other parameters regardless of `numvalues` value.
This pull request eliminates the inconsistence between the function declaration and actual behavior. If the pull request …
> Fix for numvalues parameter in Node.read_raw_history()

- asyncua/common/xmlexporter.py
Ignore the missing MinimumSamplingInterval for xml exports
Siemens S7 automatically puts some icon nodes without this attribute causing the export to crash.
See #1312
> Dont die on missing MinimumSamplingInterval Fixes #1312

- asyncua/client/client.py
- asyncua/sync.py
- tests/test_client.py
`write_values()` on `Client` always throws `UaStatusCodeError` even when the [service partially succeeded](https://reference.opcfoundation.org/Core/Part4/v105/docs/5.3) and hides the rest of the error codes other than the first one. This patch adds a `raise_on_partial_error` parameter to make it returns all status codes for each write operation.
> Add raise_on_partial_error parameter to write_values()

- asyncua/common/node.py
- asyncua/sync.py
- asyncua/ua/__init__.py
- asyncua/ua/uaerrors/_base.py
- tests/test_common.py
Add a batch version of `get_child()` method in `Node` and `UaStatusCodeErrors` for batch operations.
(Actually it seems this is a good example of the use case of `Result` type implemented by [dry-python/returns](https://github.com/dry-python/returns) and [rustedpy/result](https://github.com/rustedpy/result) instead of using exceptions)
> Add get_children_by_path()

- asyncua/sync.py
- tests/test_sync.py
Add `sync_uaclient_method` and `sync_async_client_method` to use the underlying asynchronous methods while leveraging `sync.Client`.
> Add sync_wrapper functions

- asyncua/ua/relative_path.py
- asyncua/ua/uaprotocol_auto.py
- asyncua/ua/uatypes.py
- schemas/generate_protocol_python.py
- tests/test_relative_path.py
Add `from_string()` and `to_string()` to `RelativePath` based on the [reference implementation](https://github.com/OPCFoundation/UA-.NETStandard/blob/3a378e864453e58662b47e2e3c52a61966962933/Stack/Opc.Ua.Core/Types/Utils/RelativePath.cs). Its text format conforms to [A.2 BNF of RelativePath](https://reference.opcfoundation.org/Core/Part4/v105/docs/A.2) in OPC-UA spec Part 4.
Note that this implementation still does not support non-standard `ReferenceType` (i.e., `ns!=0`) because it requires type information taken from the server to convert the passed browse name into node ID, but I think it is helpful in most use cases.
> Add from_string() and to_string() to RelativePath

- asyncua/common/structures104.py
- tests/test_common.py
See Issue #1381 :
Looking beyond the problem at hand, it might always be that a server has unexpected or corrupt data for one or more type definitions. ``load_type_definitions`` should skip such definitions with an error message and continue on. This PR provides this behavior for Enum + OptionSet types.
For regular structure types, this should already happen with the code as before (since there are up to 10 retries); however I didn't verify this.
The idea of raising all Exceptions together as `ExceptionGroup` was discarded for two reasons:
1. `load_type_definitions` returns the created objects as list, which is not possible if an Exception is raised;
2. `ExceptionGroup` was introduced in Py 3.11, requiring some hack or backport to support earlier versions.
> load_enums: skip bad enum definitions with error message

- asyncua/common/structures104.py
- tests/test_common.py
See #1381:
On one server, it was observed that OptionSets are defined using a StructureDefinition instead of EnumDefinition as suggested by the standard.
This PR enables load_enums to parse such definitions and create the enum class.
Point of discussion: Since StructureField has no means of specifying the member value, it is inferred from the index of the field within the fields array:
* Enum: Count 1, 2, 3, ..
* OptionSet: assign to bit 0, 1, 2, .. i.e. flag value 0x1, 0x2, 0x4, ...
Includes test.
Also tested against Tani Server 2.7.3 -> observed problem is fixed.
> load_data_type_definitions: Accept OptionSet / Enumeration defined via StructureDefinition

- asyncua/server/internal_server.py
- tests/test_common.py
- tests/test_subscriptions.py
- tests/test_unit.py
Those issues were not detected previously since they are linked to the recent update of ruff to version 0.0.283, which fixed an issue in the detection of this lint error.
> Fix new ruff E721 issues

- asyncua/sync.py
- tests/test_sync.py
Make `_to_sync()` function support the nested list result from some methods like `sync.Client.get_children_by_path()`.
> Support the nested list result in sync functions

- asyncua/crypto/cert_gen.py
- examples/client-with-encryption.py
- examples/server-with-encryption.py
With PR #1368 some functions are added to create and request certificates. Based on those functions a new helper method `setup_self_signed_certificate` is created. This should make it easy to add basic support to clients and servers for generating automatically certificates.
If can generated a private key and self-signed certificate when not already present. When the data range of the certificate is no longer valid it generates a new certificate.
Both the examples for client and server use with encryption are updated to demonstrate the use.
> Add and demonstrate convenient helper for self-signed certificates

- asyncua/crypto/uacrypto.py
- asyncua/server/server.py
- tests/test_crypto_connect.py
The Basic128Rsa15 connection mode was throwing the following exception when trying to connect a client:
```
File "C:\Python\Python311\Lib\site-packages\asyncua\client\ua_client.py", line 87, in _process_received_data
msg = self._connection.receive_from_header_and_body(header, buf)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Python311\Lib\site-packages\asyncua\common\connection.py", line 413, in receive_from_header_and_body
chunk = MessageChunk.from_header_and_body(self.security_policy, header, body, use_prev_key=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python\Python311\Lib\site-packages\asyncua\common\connection.py", line 124, in from_header_and_body
decrypted …
```
> Fix bad crypto argument format for basic128rsa15

- asyncua/client/ua_client.py
This PR improves the (for example SSL secure_open) error reporting from
```
Received an error: ErrorMessage(Error=StatusCode(value=2148728832), Reason=None)
Received an error: ErrorMessage(Error=StatusCode(value=2148728832), Reason=None)
```
to
```
Received an error: ErrorMessage(Error=StatusCode(value=2148728832), Reason=None)
Received an error: ErrorMessage(Error=StatusCode(value=2148728832), Reason=None)
Got error status from server: "An error occurred verifying security."(BadSecurityChecksFailed)
```
> Automatically print error text when an ua.ErrorMessage is received.

- asyncua/crypto/truststore.py
- dev_requirements.txt
- setup.py
- tests/test_truststore.py
This PR introduces a new class ` asyncua.crypto.truststore.TrustStore`.
With this `TrustStore` certificates can be validated against trusted certificates, trusted ca certificates and certificate revocation lists.
The TrustStore can handle multiple locations to collect trusted certificates and CRLs.
Test is included.
A subsequent PR is required to integrate `TrustStore` with `Client` and `Server` code.
> Adds a truststore for certficates

- asyncua/client/client.py
- asyncua/client/ua_client.py
- asyncua/common/node.py
- asyncua/sync.py
- asyncua/ua/ua_binary.py
- asyncua/ua/uatypes.py
- tests/test_subscriptions.py
- Add type hints to `struct_from_binary()` to leverage type inferences for the methods on `UaClient`
- Fix type hints on `Client.get_node()`
> Add type hints to struct_from_binary()

- asyncua/client/client.py
- asyncua/sync.py
- tests/test_client.py
- tests/test_subscriptions.py
Add `translate_browsepaths()` to `Client`, a convenient method to translate the specified relative paths into `NodeId`. It supports [RelativePath text format](https://reference.opcfoundation.org/Core/Part4/v105/docs/A.2) introduced in #1382.
> Add translate_browsepaths() to Client

- asyncua/client/client.py
- asyncua/common/shortcuts.py
- asyncua/server/server.py
- asyncua/sync.py
- tests/test_sync.py
- Add type hints to `Client`, `Server` and `Shortcuts`
- Add type hints to `sync.Client` and `sync.Shortcuts`
- Add the following missing methods to `sync.Client`:
- `connect_sessionless()`
- `disconnect_sessionless()`
- `connect_socket()`
- `disconnect_socket()`
- `set_locale()`
- `get_subscription_revised_params()`
- `get_objects_node()`
- `get_server_node()`
- `connect_and_find_servers()`
- `connect_and_find_servers_on_network()`
- `send_hello()`
- `open_secure_channel()`
- `close_secure_channel()`
- `get_endpoints()`
- `register_server()`
- `unregister_server()`
- `find_servers()`
- `find_servers_on_network()`
- `create_session()`
- `check_connection()`
- `server_policy_id()`
- `server_policy_uri()`
- `activate_session()`
- `close_session()`
- `get_keepalive_count()`
- …
> Add type hints to Client and its missing sync methods

- asyncua/client/client.py
- asyncua/crypto/validator.py
- asyncua/server/internal_server.py
- asyncua/server/internal_session.py
- asyncua/server/server.py
- examples/client-with-encryption.py
- examples/server-with-encryption.py
- tests/test_crypto_connect.py
With the hook you can register callback method with the following type `CertificateValidatorMethod`:
```
Callable[[x509.Certificate, ApplicationDescription], Awaitable[None]]
```
The method must raise an `ServiceError` exception when the certificate is invalid. The makes it possible to provide your own logic for validation.
An default implementation of such certificate validation hook is also provided by `ucrypto.validator.CertificateValidator`.
`CertificateValidator` supports checking:
- Uri
- Timerange
- Key Usage
- Extended Key Usage
- Trust
- Revoked
For the last two checks a instance of a `TrustStore` needs to be provided to `CertificateValidator`.
Which checks must be performed can be configured with `CertificateValidatorOptions`. Those are provide to the constructor of …
> Adds a certificate validation hook to the client and server

- asyncua/common/node.py
- asyncua/sync.py
- Add type hints to `SyncNode`
- Fix a type hint of `Node.add_reference()`
- Add the missing methods to `SyncNode`:
- add_reference_type()
- delete_reference()
- get_access_level()
- get_description_refs()
- get_encoding_refs()
- get_methods()
- get_referenced_nodes()
- read_data_type_definition()
- read_event_notifier()
- register()
- set_attr_bit()
- set_event_notifier()
- unregister()
- unset_attr_bit()
- write_array_dimensions()
- write_data_type_definition()
- write_value_rank()
> Add type hints to SyncNode

- CHANGELOG.md
- asyncua/client/client.py
- tests/test_client.py
Closes https://github.com/FreeOpcUa/opcua-asyncio/issues/1281
This adds `strip_url_credentials` parameter to `Client`, with a default to True.
Setting it to False is significantly less secure but may be necessary with some servers (in particular the Ignition server in my case)
> Make possible to not strip credentials in Client.server_url

- asyncua/client/client.py
- asyncua/common/subscription.py
- asyncua/server/history.py
- asyncua/server/internal_session.py
- Add type hints to `Subscription`
- Add `SubscriptionHandler` protocol class for type hinting
> Add type hints to Subscription

- asyncua/common/methods.py
I hope I did not miss anything.
Locally the tests run through; ~except for two (likely unrelated), which demanded two resource files~.
> feat: Add typehints for methods.to_variant()

- asyncua/common/manage_nodes.py
- asyncua/common/node.py
Closes #1466, Closes #1491
- fix type hints of functions which call `_parse_nodeid_qname`
- fix type hint of `add_object`
for `nodeid` and `bname`, valid combinations are only `(int, str)` and `(NodeId | str, QualifiedName, str)`.
(it's possible to put two `@overload`s to reject `(int, QualifiedName)` case)
> fix type hints of Node methods

- asyncua/server/address_space.py
- asyncua/server/internal_server.py
- asyncua/server/server.py
- asyncua/sync.py
- tests/test_server.py
- Add `set_attribute_value_callback()` to `Server`
- Make `value_callback()` trigger with `NodeId` and `AttributeIds` as parameters
It is a simplified version of #144 without async callback support.
> Add set_attribute_value_callback() to Server

- asyncua/ua/uatypes.py
Hello,
while working with an open62541 based server, I encountered an empty/null `ByteString`. The `ua_binary` implementation of ByteString (`_Bytes`) already handles this case as per the standard ([Part 6 5.2.2.7](https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.7)) and sets the value to `None`, but the implementation of `Variant` currently throws an `UaError` when a `ByteString` with value `None` is encountered. This PR adds `ByteString` to the allowed `VariantType`s that can be `None`.
> Allow ByteString Variant to be None

- asyncua/crypto/uacrypto.py
Only log a warning if the subject alternate name is not as the opc ua specs.
Fixes #1544
> crypto change subject alternate errors to warning

- asyncua/server/address_space.py
- asyncua/server/internal_server.py
- asyncua/server/server.py
- tests/test_server.py
This method allows to set a custom setter function on a per-attribute basis. This setter function will then be called by `write_attribute_value()` instead of writing the attribute value directly. This allows for custom logic to be implemented by the user (such as checking if the value to be written is within a certain range) and if not, an appropriate error can be raised from that setter, preventing the write and notifying the client about the occurred error.
Also, see discussion #1563 for some more background info about the use case of this method.
> Add `set_attribute_value_setter()` method to server

- asyncua/server/uaprocessor.py
I noticed that raising a `BadOutOfRangeError` in a server callback set through `Server.subscribe_server_callback` resulted in a *BadInternalError* on the client side (tested with UaExpert) rather than the expected *BadOutOfRange*. But raising a
`ServiceError(ua.StatusCodes.BadOutOfRange)` instead would show the the expected *BadOutOfRange* error in the client.
The reason for this idiosyncrasy was that `UaStatusCodeError`s were not explicitly caught. Therefore the "default" `except Exception` handler would be used which resulted in a
`ua.StatusCode(ua.StatusCodes.BadInternalError)` to be sent to the client instead of the actual status code of the error that occurred.
This commit changes the behavior such that the status code of `UaStatusCodeError`s is respected the same way as it's already …
> Fix handling of `UaStatusCodeError`s in `UaProcessor.process_message`

- tests/test_server.py
There exists a unittest, which could attest that loading shelf files does currently not work.
This migrates it from unittest to the new pytest format and alters the shelf_file invocation which was provided in `__init__()` before and is now done in `init()`.
> test: Migrate deactivated unit to pytest

- asyncua/ua/uatypes.py
- tests/test_common.py
- tests/test_unit.py
NodeId calculation from string failed when the Identifier portion contained semicolons.
According to the OPC-UA spec (https://reference.opcfoundation.org/Core/Part3/v104/docs/8.2.4 and https://reference.opcfoundation.org/Core/Part3/v105/docs/8.2.4) there are no limitations to string node identifiers within the unicode charset - they should only not contain unicode control characters. I've already seen some OPC-UA servers where this occurs (see example below).
Example:
The node `ns=9;s=Line1.nsuri=MACHINE.NS;s=MACHINE.NS.State.Running` is regularly deconstructed as NamespaceId `9`, Identifier Type `String`, Identifier `Line1.nsuri=MACHINE.NS;s=MACHINE.NS.State.Running`. Previously this was parsed to have the Identifier `MACHINE.NS.State.Running`, now it is as expected.
> Fix NodeId parsing for nodes containing semicolons in string identifiers

- asyncua/crypto/uacrypto.py
Address the following deprecation warnings when using python 3.12
`2024-03-04 10:11:02,506 ¦ py.warnings ¦ WARNING ¦ warnings ¦ _showwarnmsg ¦ 109 ¦ 0 ¦ 0 ¦ c:\....\opcua-asyncio\asyncua\crypto\uacrypto.py:334: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
if cert.not_valid_after < now:
2024-03-04 10:11:02,507 ¦ py.warnings ¦ WARNING ¦ warnings ¦ _showwarnmsg ¦ 109 ¦ 0 ¦ 0 ¦ c:\....\opcua-asyncio\asyncua\crypto\uacrypto.py:337: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_before_utc.
if cert.not_valid_before > now:`
> Python3.12: fix CryptographyDeprecationWarning

- setup.py
If the version of pyOpenSSL is not specified, it may lead to the `AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?` error  due to the newer version of cryptography.
> pyOpenSSL, lib has no attribute X509_V_FLAG_NOTIFY_POLICY problem

- asyncua/client/client.py
- asyncua/common/xmlimporter.py
- asyncua/server/server.py
- tests/test_common.py
To the `import_xml` an optional argument `auto_load_definitions` is added. Default is True.
Case:
With commit https://github.com/FreeOpcUa/opcua-asyncio/commit/de8269e4dadcbc2e12773a35b415f55e54e8709c `import_xml` automatic load(on the fly code generation) the type defintions.
When using your own extension object and enum implementation (with `ua.register_extension_object`  `ua.register_enum`) this is unwanted behaviour.
Previous work flow was:
* import xml
* register own extension object and enum implementations
* for the remain stuff call `load_data_type_definitions()`
To make this possible again an option is required to prevent the auto load definitions when calling the `import_xml` method.
> [xmlimporter] Support to make auto load type definitions optional

- asyncua/client/client.py
- asyncua/server/server.py
This fixes a couple of `pyright` warnings I noticed with tests.﻿
See https://github.com/FreeOpcUa/opcua-asyncio/pull/1179 for context
> Fix type hints to allow Path

- asyncua/server/internal_subscription.py
Addresses https://github.com/FreeOpcUa/opcua-asyncio/issues/1267 and https://github.com/FreeOpcUa/opcua-asyncio/issues/116. As discussed in [this comment](https://github.com/FreeOpcUa/opcua-asyncio/issues/116#issuecomment-2155642372), in order to comply with [section 5.13.1.1](https://reference.opcfoundation.org/Core/Part4/v104/docs/5.13.1.1) part 8 of the spec, we should close the subscription and delete all monitored items:
> [Subscriptions](https://reference.opcfoundation.org/search/17?t=Subscriptions) have a lifetime counter that counts the number of consecutive publishing cycles in which there have been no [Publish](https://reference.opcfoundation.org/search/17?t=Publish) requests available to send a [Publish](https://reference.opcfoundation.org/search/17?t=Publish) response for the …
> Stop expired subscriptions

- asyncua/server/internal_session.py
- asyncua/server/internal_subscription.py
- asyncua/server/subscription_service.py
As discussed [here](https://github.com/FreeOpcUa/opcua-asyncio/pull/1654#issuecomment-2162116152), we need to clean up some subscription objects when a subscription deletion within `internal_subscription.py` due to an exceeded `RevisedLifetimeCount`. In this PR, I implement a callback that cleans up the subscription objects in the subscription service that is called when the subscription is stopped in this fashion.
> Add callback to delete subscriptions

- asyncua/server/internal_session.py
- asyncua/server/uaprocessor.py
- asyncua/ua/uatypes.py
- tests/test_connections.py
As discussed [here](https://github.com/FreeOpcUa/opcua-asyncio/issues/116#issuecomment-2155642372), to comply with [section 5.6.2](https://reference.opcfoundation.org/Core/Part4/v104/docs/5.6.2) of the spec, the server should close a session that is inactive within its session timeout:
> [Sessions](https://reference.opcfoundation.org/search/17?t=Sessions) are terminated by the [Server](https://reference.opcfoundation.org/search/17?t=Server) automatically if the [Client](https://reference.opcfoundation.org/search/17?t=Client) fails to issue a [Service](https://reference.opcfoundation.org/search/17?t=Service) request on the [Session](https://reference.opcfoundation.org/search/17?t=Session) within the timeout period negotiated by the …
> Add server-side session watchdog

- asyncua/server/address_space.py
Currently i am using ```set_attribute_value_callback``` and ```set_attribute_value_setter``` on the Server. I do this to be able to manage the Value in my own Data structure.
Currently i have the problem, that when ever the Value is written by ```write_attribute_value``` i can not read the value again.
This is because ```attval.value_callback``` is reset to ```None``` even if a value setter is used.
This causes the Value and the value callback to be ```None```, which will result in ```None``` being returned by ```read_attribute_value``` which cant be serialized.
This fixes this Problem by only setting the ```attval.value_callback``` to ```None``` if no value Setter is defined.
> Don't reset attribute_value_callback on write

- asyncua/common/methods.py
This way we can decorate a function which is already decorated with `@uamethod` again and things like `func.__name__` will correctly return the name of the decorated function and not `wrapper`.
E.g., the following will now correctly print `Calling my_method ...`. Without `@wraps(func)` it would have printed `Calling wrapper ...`:
```py
from functools import wraps
def my_decorator(func):
@wraps(func)
def wrapper(*args, **kwargs):
print(f"Calling {func.__name__} with {args=} and {kwargs=}")
@my_decorator
@uamethod
def my_method(parent, arg1, arg2):
print(f"my_method called with {arg1=} and {arg2=}")
```
> Add `@functools.wraps(func)` to the `wrapper` function of `@uamethod`

- asyncua/common/callback.py
- asyncua/common/statemachine.py
- asyncua/common/structures.py
- asyncua/crypto/security_policies.py
- asyncua/server/address_space.py
- asyncua/server/history_sql.py
- asyncua/server/internal_session.py
- asyncua/sync.py
- asyncua/tools.py
- examples/client-example.py
- examples/client_to_kepware.py
- examples/client_to_prosys.py
- examples/server-example.py
- examples/server-ua-python-mirror.py
- examples/sync/client-example.py
- examples/sync/client_to_prosys.py
- examples/sync/server-example.py
- ruff.toml
- test_external_server.py
- tests/test_common.py
- tests/test_connections.py
- tests/test_subscriptions.py
- tests/test_unit.py
- tests/test_xml.py
Enable the [pyupgrade related rules in ruff](https://docs.astral.sh/ruff/rules/#pyupgrade-up), to automatically apply some the the code updates when the minimal Python version is increased.
> Enable pyupgrade in ruff

- CHANGELOG.md
- asyncua/common/node.py
- asyncua/sync.py
Fixed function signature of `read_array_dimensions` in asyncua/common/node.
ArrayDimentions is always a `list` of `int`s because OPC UA has support for multidimentional arrays. This is specified in the OPC UA standard at the end of [this](https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.16) page. But the return type in asyncua was is specified as `int`. This can generate false type-checker errors. Fix is to just change signature. The fucntion already correctly returns a list of integers.
Let me know if you want me to add a changelog entry also 😊
> Fixed function signature in `Node`

- asyncua/crypto/permission_rules.py
- asyncua/crypto/security_policies.py
- asyncua/server/server.py
- examples/server-with-encryption.py
- tests/test_permissions.py
I had issues using a Siemens S7 PLC as OPC UA client reading values out of an asyncua server. It turned out that it used RegisterNodes, which is currently only allowed with write permission.
According to https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.5, the RegisterNodes Service can be used by Clients to register the Nodes that they know they will access repeatedly (e.g. Write, Call).
The service itself neither reads or writes data, it's just an optional optimization which is implemented as noop by asyncua.
> Fix SimpleRoleRuleset

- asyncua/server/server.py
The opc-ua client backend open62541 scans for endpoint tokens' security URI on connection. This PR to resolve the case that open62541 to skip token which is missing that URI.
> Add policy URI to each endpoint token's SecurityPolicyUri

- asyncua/common/connection.py
- asyncua/server/internal_server.py
- asyncua/server/server.py
- asyncua/sync.py
- tests/test_crypto_connect.py
- tests/test_password.py
> Identity tokens

- asyncua/client/client.py
- The updated ServerNonce was not saved after activate_session, which means that subsequent activate_sessions would fail with BadIdentityTokenInvalid.
- The self._password attribute of Client was checked in _add_user_auth function, instead of its own password argument.
> Fixes for using activate_session to change users.

- asyncua/client/client.py
- asyncua/client/ha/reconciliator.py
- asyncua/common/connection.py
- asyncua/common/copy_node_util.py
- asyncua/common/utils.py
- asyncua/common/xmlimporter.py
- asyncua/server/history_sql.py
- asyncua/server/internal_session.py
- asyncua/server/user_managers.py
- asyncua/ua/uatypes.py
- tests/test_crypto_connect.py
Added conditionals to log limit updates only when changes are detected, reducing unnecessary log noise. This applies to both server and client limit updates in the connection logic.
On the server these fake limit update logs cause noise and are mostly false positives.
Example:
> Update connection limit logging to check for changes

- asyncua/ua/uatypes.py
@oroulet not sure why Number is missing!? its just an abstract BaseDataType....
```
(env) C:\Users\Andreas\Documents\GitHub\opcua-tutorial>C:/Users/Andreas/Documents/GitHub/opcua-tutorial/env/Scripts/python.exe "c:/Users/Andreas/Documents/GitHub/opcua-tutorial/client/BaseClient copy.py"
WARNING:asyncua.client.client:Requested session timeout to be 300000ms, got 3000000ms instead
WARNING:asyncua.common.structures104:renamed 3DVector to _3DVector due to Python syntax
WARNING:asyncua.common.structures104:renamed 3DCartesianCoordinates to _3DCartesianCoordinates due to Python syntax
WARNING:asyncua.common.structures104:renamed 3DOrientation to _3DOrientation due to Python syntax
WARNING:asyncua.common.structures104:renamed 3DFrame to _3DFrame due to Python syntax …
```
> add: Number in uatypes.py

- asyncua/ua/uatypes.py
According to ObjectIds, [DataValue = 23](https://github.com/FreeOpcUa/opcua-asyncio/blob/447bdf7596ba07c0aac239919e28471b0b3efd45/asyncua/ua/object_ids.py?plain=1#L28), and not 25 as it was before this commit. [25 is DiagnosticInfo](https://github.com/FreeOpcUa/opcua-asyncio/blob/447bdf7596ba07c0aac239919e28471b0b3efd45/asyncua/ua/object_ids.py?plain=1#L30), which can also be seen on line 1137 in the uatypes.py file.
(this is my first PR in this repo, and I found it while "just browsing around", so feel free to tell me if I'm completely off here 😉)
Edit: Now using `ObjectIds.DataValue` instead of `23` to make it more obvious.
> fix: NodeId change for class DataValue

- asyncua/common/structures104.py
This PR adds support for loading data types definitions for types that have StructureType set to StructureWithSubtypedValues, and to read the corresponding values. It does this by simply wrapping the types that should be allowed to have subtypes in a typing.Annotated, which ends up giving the right result because of how ua.uatypes.type_allow_subclass is defined. I'm not sure if this is the most proper way of doing this
As far as I can tell this is not enough to *write* such a value, or at least I haven't manage to figure out how to set that up. Since I wasn't able to write any values I also weren't able to add any tests that check reading structures with subtypes. I have however successfully tested loading data types and reading values from an external server
There is also the …
> Add support for reading structure with subtyped values

- schemas/generate_address_space.py
Fixes #1529.
Add references after all nodes has been processed, when we know the respective NodeClass of the TargetNode. Reused schema version 1.05.01, to not introduce additional changes to the address space.
I also fixed the generation of binary_address_space.pickle, which probably wasn't up-to-date before, unless the generator has been run twice. Not sure if this file is needed at all, at least it's not used by asyncua itself.
> Fix Nodeclass in ReferenceDescriptions of UA-Nodeset

- asyncua/common/xmlimporter.py
- asyncua/server/address_space.py
Followup on #1529, #1794.
As a side-effect, specifying a non-existing TypeDefinition in an AddNodesRequest now leads to BadTypeDefinitionInvalid. For loading UA-Nodeset, this error is already handled in PostponeReferences. Fixed node sorting in XmlImporter.
Previously, some ReferenceDescriptions for non-existing TypeDefinitions also lacked BrowseName and DisplayName.
> Fix ReferenceDescriptions for TypeDefinition

- asyncua/ua/ua_binary.py
- tests/test_unit.py
Some old OPC/UA implementations omit the length when building ExtensionObjects and instead specify -1.  For interoperability, assume this means the rest of the buffer.  This behavior aligns with a [recent fix](https://github.com/OPCFoundation/UA-.NETStandard/commit/a887f909f1d314cfa7c32989628afa754984c4f1) to the [OPC Foundation's reference implementation](https://github.com/OPCFoundation/UA-.NETStandard).
I've added a UT (test_extension_object_missing_length), and confirmed that it fails before the fix and passes after... and confirmed that no other UTs have been broken.  This is the first time I've contributed to this repo, so please let me know if there's anything else I should do!
Fixes #1801
> Parse ExtensionObjects with missing length (= -1)

- examples/server-events-history.py
- examples/server-example.py
- examples/server-methods.py
- examples/sync/server-example.py
datetime.datetime.utcnow() is deprecated.
So I use ".now(UTC)"" and "from datetime import datetime, UTC". And fix typos. Optimize imports
> Aware time in the examples

- asyncua/common/structures104.py
If loading data types out of order it is expected to get an exception in `load_data_typ_definitions`. We shouldn't report this to the log file until we give up on loading types.
This also fixes an error in the log format string, which leads to an exception when logging.
> Avoid logging non-exceptional exception, and fix error in log format

- asyncua/ua/uatypes.py
Typo in the LocalizedText()'s error messages. And some unresolved references in docstrings.
> Typo fix in uatypes.py's error messages and docstrings

- asyncua/common/connection.py
Fixes regression from #1729.
In the PR mentioned above, host_certificate has also been set for SecurityPolicyNone. This was needed for having password encryption on an unencrypted channel.
This now broke my setup with AspenTech Inmation. According to https://reference.opcfoundation.org/Core/Part6/v105/docs/6.7.2.3, SecurityHeader.SenderCertificate shall be null if the Message is not signed.
As already mentioned in the PR above, SecurityPolicies shouldn't be misused as data containers for stuff with better belongs to server or client objects. I currently don't have time to clean that up, so I only fixed it with omitting SenderCertificate when using MessageSecurityMode.None_.
> SenderCertificate shall be null if the Message is not signed

- CHANGELOG.md
- asyncua/crypto/uacrypto.py
- tests/test_cert_chain.py
This PR enhances the x509_from_der function to properly handle certificate chains by extracting and using the first certificate when a chain is detected.
When connecting to certain OPC UA servers that send certificate chains, the library currently fails with the error:
```ValueError: error parsing asn1 value: ParseError { kind: ExtraData }```
This happens because the cryptography library's `load_der_x509_certificate` function expects a single certificate, but receives a chain of certificates.
- Modified x509_from_der to catch the specific ValueError with "extradata" in the message
- Added DER parsing logic to extract just the first certificate from the chain
- Added comprehensive docstrings and comments explaining the certificate chain handling
- Created tests to verify the fix works …
> Include support for x509 certificate chains in DER format

- asyncua/server/uaprocessor.py
The ClientNonce and also the peer_certificate can be set to None, this fixes the resulting TypeError
```
File "...\Python312-32\Lib\site-packages\asyncua\server\uaprocessor.py", line 147, in process_message
return await self._process_message(typeid, requesthdr, seqhdr, body)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "...\Python312-32\Lib\site-packages\asyncua\server\uaprocessor.py", line 213, in _process_message
data = self._connection.security_policy.peer_certificate + params.ClientNonce
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't concat NoneType to bytes
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```
fixes #1821
> ClientNonce and/or peer_certificate may be None
