asyncua/common/subscription.py, tests/test_subscriptions.py
Subscription.unsubscribe() now supports a list of handles (I added two tests for that).
Docstrings in Subscription were updated and typings for handles were added.
=> Subscription #39

asyncua/client/client.py, asyncua/client/ua_client.py
I changed the unit timeout parameter of all client methods to seconds.
Fixes #18
=> Fix for issue #18

asyncua/common/ua_utils.py, asyncua/common/xmlimporter.py, asyncua/common/xmlparser.py, asyncua/ua/uatypes.py, tests/test_unit.py, tests/test_xml.py
I implemented the Locale field in LocalizedText class in the same way as it was done for Text. Some affected methods were changed accordingly. Also, I made changes in xmlimporter and xmlparser to support import of ListOfLocalizedText. I implemented a few test cases and then I run testing to validate the changes.
=> LocalizedText extended to handle Locale

asyncua/common/manage_nodes.py, asyncua/server/internal_session.py, asyncua/server/server.py
=> Fix for #74 - make InternalSession.add_method_callback sync.

.travis.yml, asyncua/client/client.py, asyncua/client/ua_client.py, asyncua/common/event_objects.py, asyncua/common/manage_nodes.py, asyncua/common/node.py, asyncua/common/ua_utils.py, asyncua/common/xmlexporter.py, asyncua/crypto/security_policies.py, asyncua/server/event_generator.py, asyncua/server/history.py, asyncua/server/history_sql.py, asyncua/server/internal_session.py, asyncua/server/server.py, asyncua/server/uaprocessor.py, asyncua/ua/uaprotocol_hand.py, asyncua/ua/uatypes.py, dev_requirements.txt, setup.py, tests/conftest.py, tests/test_client.py, tests/test_server.py, tests/test_xml.py
Fix for #60 
Migrate to aiosqlite for the sql history.
The sql history tests were still disabled. Some are failing - i will investigate.
=> Fix 60 aiosqlite

asyncua/crypto/uacrypto.py, asyncua/server/server.py
Hey,
I use certificates in pem format but with .crt and .key 
now its enabled
=> Certificates use pem format without .pem ending

asyncua/server/server.py
This allows consumers of the library to set buildinformation.
Additionally this fixes buildinformation representation in individual
nodes (like ua.ObjectIds.Server_ServerStatus_BuildInfo_ProductUri).
Before the individual buildinfo nodes haven't been populated. Now,
they are kept in sync with the buildinfo struct.
=> Allow customizing buildinfo

asyncua/server/internal_session.py
Hey,
I think this is very useful.
I had no other idea where to solve this problem but I think this works fine.
=> limit the max amount of connections

tests/test_connections.py
Now it should be ok.
Sorry again.
=> test limit connections

asyncua/common/xmlexporter.py
Fixes xml_method export issue #129 .
=> Outdent method for Reference adding.

asyncua/client/client.py, asyncua/crypto/uacrypto.py, asyncua/server/server.py
Hey,
now you can open an encrypted key.
best regards
=> enables to open encrypted keys with a password

asyncua/client/client.py
Default ClientSignature.Algorithm reference to AsymmetricSignatureURI
Similar to https://github.com/FreeOpcUa/python-opcua/pull/945
Small test: https://pastebin.com/SxUSnFi0
=> [OpcuaClient] Default ClientSignature.Algorithm reference

asyncua/client/client.py
These were throwing errors in a downstream sphinx documentation build :)
=> Clean up some documentation formatting

asyncua/sync.py
- Client.set_security
- Client.connect_and_get_server_endpoints
- Node.get_path
- Node.get_node_class
- Node.get_attributes
=> Added missing methods to sync client:

asyncua/tools.py
Fixed #149 
I did not find any tests to fix.
=> Fixed uahiostoryread

asyncua/client/client.py
Enabled Basic256Sha256-alike certificate user authentication for me. Current implementation limited to Basic256 equivalent.
=> retrieve hash algorithm from user token #137

.gitignore, asyncua/client/client.py, asyncua/server/server.py
Add async and await to get_namespace_array methods
Add /venv to gitignore
Will fix #180
=> Add async and await to get_namespace_array methods

asyncua/sync.py
=> Add get_properties method to sync version of Node

tests/test_permissions.py
=> change tests to allow anonymous users to get endpoints

examples/client_to_kepware.py
https://github.com/FreeOpcUa/opcua-asyncio/issues/225
=> Update client_to_kepware.py - #225

asyncua/server/uaprocessor.py
=> Don't return AccessDenied on FindServers requests

.gitignore, asyncua/common/type_dictionary_buider.py, asyncua/common/xmlexporter.py, asyncua/ua/uatypes.py, docs/conf.py, schemas/generate_event_objects.py, schemas/generate_model.py, schemas/generate_protocol_python.py, tests/test_sync.py
Add pretty argument to docstrings
Fix warning in Travis tests about invalid escape sequences
Add new line to be PEP8 conform
Remove unused import
Remove doubled expressions
remove redundant parenthese
=> Fix smaller issues

.travis.yml, asyncua/tools.py, examples/client-minimal.py, tests/test_tools.py
This parameterized test catches https://github.com/FreeOpcUa/opcua-asyncio/issues/106
=> add basic test for CLI tools

.travis.yml
=> Add Python 3.7 and 3.8 (actual stable) to Travis

asyncua/client/ua_client.py
=> Stop client acknowledging KeepAliveMessags

examples/server-enum.py
(Fixed the referenced commit links)
Was previously fixed in https://github.com/FreeOpcUa/opcua-asyncio/commit/4327f4f60d5473b97ae9491be9103b872472a925 and subsequently reverted in https://github.com/FreeOpcUa/opcua-asyncio/commit/6df858e28cc4f9ba964288ca1ffa3aa2da8d89ec.
=> Improve enum example

asyncua/server/binary_server_asyncio.py
=> Joey faulkner bugfix/server memory leak

asyncua/ua/uatypes.py, tests/test_unit.py
=> Check all zero ID instead of single zero in ID.

asyncua/server/server.py
=> Add default value for ServiceLevel at server start

.travis.yml, README.md
Drop Python 3.6 support in travis tests
Upgrade test cases from ubuntu xenial to bionic
Update README
=> Drop Python 3.6 support in travis tests

asyncua/client/ua_client.py
Alternative to #321, possible fix for #313.
Instead of making the receive loop async and using a lock, I use an extra field to pass request parameters (to the parse job) and result (for the return statement) back and forth, meaning there's a new condition of not being able to make a new request if the old one is still running.
Of course, a lock could be used to keep new requests waiting and execute them immediately after, but renewal this quickly is probably just not going to happen.
... he said foreshadowingly. *thunder cracks in the distance*
Forgot to mention that I tried to add_done_callback to the future, but that didn't work. It appears the callback is scheduled asynchronously.
=> new approach to the new security token race condition

asyncua/common/manage_nodes.py, asyncua/common/node.py, asyncua/ua/uatypes.py
Added Option for create_object() -> instantiate_optional. No breaking change just added options for more control if you create a object.
=> added instantiate_optional support on create object method and possible fix for #307

.travis.yml, asyncua/common/structures.py, asyncua/common/xmlparser.py, setup.py
Replace iter() with iterfind()
Remove lxml from setup.py
Remove done FIXME Graffitti
Remove lxml from travis
Tbh, I have no clue why I was wandering in other files in the old draft, but it seems to work....
A fix for #299
=> Replace lxml with xml.etree.ElementTree

asyncua/common/events.py
Event types can not only contain properties, but also variables. For example the ConditionType, which is the foundation of Alarms and Conditions, contains variables. This change adds the variables to the generated event filter and event object.
https://reference.opcfoundation.org/v104/Core/docs/Part9/5.5.2/
Without the change the Variables in ConditionType of VariableType like EnabledState, Quality or Comment cannot be accessed in the Event with generated filter select clause.
=> Propose: Add variables to generated event filter and event object

asyncua/server/server.py, asyncua/tools.py
uals fails with -l option and subscription loop did not properly handle task completion.
=> Fix uals -l asyncio error

asyncua/common/shortcuts.py, asyncua/common/xmlimporter.py, asyncua/common/xmlparser.py, tests/test_requirement_fail.xml, tests/test_requirement_pass.xml, tests/test_xml.py
First step of a solution for #353
=> Check xmlimport requirements

asyncua/common/xmlimporter.py
=> Fix issue of comparing existing Servermodels with XML-files to import

asyncua/client/client.py
https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.2/
=> added browse multiple nodes in one ua call

asyncua/client/client.py
@oroulet good that you asked... somehow i missed that only "nodeClassMask" 0 is returning all! sorry about that -_-°
=> unlucky default value for ResultMask!

asyncua/common/shortcuts.py
Removed duplicated instance: `self.types = Node(server, ObjectIds.TypesFolder)`
=> removed the duplicated self.types

asyncua/common/events.py
- Renaming "fields" to "attributes" on places where it was used as a generalization for properties and variables. Because fields already has a different meaning in "to_event_fields" and "from_event_fields". That was irritating.
- Optimize performance in select_clauses_from_evtype
=> Events refactoring: Renaming and performance

tests/test_subscriptions.py
- adds test for events with variables like in AlarmConditionType
- adds test which performs some checks in event filter
=> Add test case for events with variables and test for event filter

asyncua/tools.py
Replace run method with asyncio.run, since it is standard in python3.7
Add missing awaits in Coroutines
Fix smaller Codestyle issues
=> Remove python version check in tools.py

asyncua/common/xmlimporter.py
Add method to add reverse references, if missing
fix for #307
=> Fix missing references while import xml files

asyncua/server/server.py
https://github.com/FreeOpcUa/opcua-asyncio/issues/457
=> added typecheck for buildinfo

asyncua/common/xmlimporter.py, tests/custom_nodesns_2.xml, tests/custom_nodesns_3.xml, tests/custom_nodesns_4.xml, tests/test_xml.py
Made some changes to suppress migration, via optional parameter.
=> Fix for importing nodesets with different order

asyncua/ua/uatypes.py
fixes: https://github.com/FreeOpcUa/opcua-asyncio/discussions/528#discussioncomment-557072
and https://github.com/FreeOpcUa/opcua-asyncio/pull/461
=> fix order of DataValue attritbutes

asyncua/server/internal_server.py, asyncua/server/server.py, tests/test_server.py
=> server read_attribute_value

asyncua/sync.py
Added the function I needed in the SyncWrapper.
The export_xml_by_ns() function is currently not working for me, but I am not sure if this is caused by the SyncWrapper or some other issue.
=> Adding more sync functions

asyncua/crypto/security_policies.py
Update deprecated Security Policies to use the correct certificate property names. Should fix issue #193
=> Update deprecated Security Policies to use the correct certificate property names

asyncua/client/client.py
Probably a bad copy/pasta during code formatting, and it catches my eyes all the time now ;)
=> Remove minor glitch from #585

asyncua/server/address_space.py, examples/server-example.py, tests/test_common.py, tests/test_custom_structures.py, tests/test_permissions.py, tests/test_xml.py
This is a very fast implmentation but it does not check for the reall type but but for the previous type. This is not exactly the same... but maybe it is OK
=> add TypeCheck server side

asyncua/common/xmlimporter.py
fixes #611 
also https://github.com/FreeOpcUa/opcua-asyncio/issues/594#issuecomment-866763055
__NOTE__ : Sorry for the previous PR. It was having changes from my fork's master where I applied https://github.com/FreeOpcUa/opcua-asyncio/pull/517#issue-602313624 because I need it. In this PR I remove those changes (sorry for the trailing of unrelated commits you see with this PR, I should not have changed my fork's master :( )
=> Fix #611 scrambled datatypes nodeids

asyncua/ua/uaprotocol_auto.py, schemas/generate_protocol_python.py
Fixed generation for default values for GUID. Now an empty GUID is generated.
=> Fix default GUID

tests/test_common.py, tests/test_sync.py
- Prevent the test suite from creating files in the current working directory
=> Prevent test suite from creating files in the current working dir

asyncua/crypto/security_policies.py, asyncua/ua/uatypes.py
[Augmented assignment statements became available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments").
:thought_balloon: Thus improve three source code places accordingly.
=> Convert three statements to the usage of augmented assignments

asyncua/client/ua_file_transfer.py
Cache the nodes of potentially multiple-used FileType methods.
=> Reduction of network access

tests/conftest.py
According to the logs of the recent test failure, there's a small window when we test the connection is established where we have a socket connected but don't have the session created yet, and this is throwing an exception when trying to disconnect because the renew loop is not yet created.
```
=================================== FAILURES ===================================
_________________________ TestHaManager.test_reconnect _________________________
self = <tests.test_ha_client.TestHaManager object at 0x7f8614996e30>
ha_client = <asyncua.client.ha.ha_client.HaClient object at 0x7f86158c9ea0>
@pytest.mark.asyncio
async def test_reconnect(self, ha_client):
await ha_client.start()
await wait_clients_socket(ha_client, UASocketProtocol.OPEN)
for c in ha_client.get_clients():
> …
```
=> [HaClient] Fix test race condition

asyncua/tools.py
uasubscribe didn't show data change notifications, and this PR fixes the problem.
=> Fixes data change notifications problems in uasubscribe tool

asyncua/common/xmlexporter.py, asyncua/common/xmlimporter.py, asyncua/common/xmlparser.py, tests/test_xml.py
Allow XMLElement, ExpandedNodeId, StatusCode and QualifiedName for xmlimport and export.
=> XML import/export add more supported valuetypes

asyncua/server/internal_subscription.py
I experienced a memory leak [issue](https://github.com/FreeOpcUa/opcua-asyncio/discussions/750) with the library earlier, when there  are too many not acknowledged publish results stored.
I think it would make sense to limit the number of not acknowledged result we stored.
=> limit size of not-acknowledged results

asyncua/common/statemachine.py
Fixed parameter named from lowercase to CameCase in statemachine.install.
=> Fixed Parametername varianttype -> VariantType

asyncua/common/subscription.py
Slightly improve performance when `datachange_notification` handler method is a coroutine, by using `asyncio.gather` to ensure calls are parallelised 
MacBook Pro (16-inch, 2019)
Python 3.8.10
opcua-asyncio[master]
Subscription for 1000 variables changing with frequency of 1Hz
Subscription publish interval - 5 sec
```py
class OpcUaDataGatewayService(BaseOPCService):
...
async def process_event(self, event, node, value):
event_data = await self.data_provider.serialize(event, value=value)  # get event node attributes as dict
measurement = self._make_measurement(node_measurement_config, **event_data)
await self.send_message(measurement)  # buffering happens in this function so it's pretty fast
async def datachange_notification(self, node, value, event):
await self.process_event(event, node, …
```
=> fix: parallel async datachange_notification calls

asyncua/common/structures.py
=> remove useless print

asyncua/common/structures104.py, examples/server-custom-structures-and-enums.py, tests/test_common.py
- Fix default value for structs with lists
- Rename server-custom-structures-amd-enums.py
- Fix Enum in server-custom-structures-amd-enums.py
Fixes #893 and #892
=> struct arrays in custom types

asyncua/client/client.py
=> Set Client locale

asyncua/ua/ua_binary.py, tests/test_common.py
Fixed enum regression from #873
=> Fix enum regression

asyncua/common/structures.py, tests/custom_extension_with_optional_fields.xml, tests/test_custom_structures.py
based on https://github.com/FreeOpcUa/python-opcua/pull/1451 from @deeTEEcee
=> Add support for pre 1.04 optionsets

asyncua/common/events.py, tests/test_subscriptions.py
=> fix wrong return type

asyncua/client/ha/reconciliator.py
- help for type check
- highlight function arguments types
Closes #885
=> Reconciliator: added function definitions

asyncua/client/ha/reconciliator.py, asyncua/client/ua_client.py, asyncua/common/events.py, asyncua/common/statemachine.py, asyncua/common/structures104.py, asyncua/server/address_space.py, setup.cfg, tests/test_unit.py
how to get around the following warnings i don't know. i would need help. 
part of #908
#909
=> mypy, test enable attr-defined

examples/client-with-encryption.py
=> Fix server address

asyncua/client/ua_client.py
=> fix _open_secure_channel_exchange typehints

asyncua/common/structures104.py
If a DataType Node didn't contain a DataTypeDefinition, it wasn't browsed for childs.
#946
=> parse all datatype nodes for childs

asyncua/common/manage_nodes.py, tests/test_common.py
=> Add modeling rule for method arguments

asyncua/client/client.py, asyncua/common/xmlimporter.py, asyncua/server/server.py, asyncua/sync.py
In non strict_mode most errors are just logged an the import continues.
=> XMLImport relaxed mode

asyncua/ua/uatypes.py, tests/test_common.py
Found in #946 and proposed fix by @BenediktEnger 
added tests
=> Structs104: Fix alias of basetype

asyncua/common/xmlexporter.py
Hi,
for my usecase (B&R PLC as OPCUA server) `XmlExporter` was raising some `BadAttributeIdInvalid` errors on fields that were optional in the first place. 
I suspect that some time ago `raise_on_bad_status=True` was added as a default to `Node.read_attribute` and that caused different behavior here, since in almost all of the cases the the value is checked before working with it.
=> Fixed XmlExporter raising BadAttributeIdInvalid on optional fields

asyncua/common/structures104.py
This should fix #941, and other cases of importing XML nodesets with custom data structures.
The original problem was that each node would only be compared with its direct dependencies, instead of considering the whole type dependency chain.
=> structures104: sort type dependencies correctly

asyncua/client/client.py
Fix cases where a secure channel can be leaked
=> Always close SecureChannel

asyncua/common/events.py
See #964 
Had the same problem with other sdk a long time ago and wrote my own EventFilter, with this pr the automatic generation works.
=> EventFilter set typedefinitionid

asyncua/client/ua_client.py, schemas/generate_model_from_nodeset.py, schemas/generate_protocol_python.py
cfr. https://github.com/FreeOpcUa/opcua-asyncio/issues/983
=> bugfix generating uaprotocol_auto

asyncua/common/xmlimporter.py
Variable is set in try block, but would be appended to the list after the except block
=> fixed an UnboundLocalError

asyncua/server/internal_session.py, asyncua/server/uaprocessor.py, tests/test_crypto_connect.py
All services that require a active session are now check. Before it was possible to access these services without authentication, because this is done in activate session. See #1014
=> check if session is activated

asyncua/common/node.py
=> fix Node register

asyncua/server/binary_server_asyncio.py, tests/test_connections.py
fix test after rebase
server handle malformed packets
close connection on error
reorder imports
change test
=> server handle malformed packets

asyncua/client/ua_client.py, asyncua/common/connection.py, asyncua/server/binary_server_asyncio.py, asyncua/server/uaprocessor.py, tests/test_server.py
Check the limits of messages to prevent DOS from unlimited chunks. (CVE-2022-25304 #1023)
=> Check limits of messages (CVE-2022-25304)

.gitignore, schemas/update_ua_nodeset.py
- Add windows support
- Allow targeting a tag and/or branch
=> enhance nodeset generator

schemas/generate_address_space.py
Default value should be False
Fixes #1084
=> AddresSpace fix DataTypes IsAbstract

asyncua/common/ua_utils.py
#1152
data_type_to_variant_type is miss handling some nodeids (Number, Integer, UInteger, BaseDataType and Image). This function is used in read_data_type_as_variant_type.
=> handle missing nodeids in data_type_to_variant_type 

asyncua/common/connection.py
=> Use info log level for client and server limit update message

asyncua/common/xmlparser.py
Parsing of the historizing variable is missing.
=> Add historizing variable to parse node

asyncua/common/events.py, asyncua/common/subscription.py
=> optional where clause generation

asyncua/server/address_space.py
=> MethodCall allow None InputArguments

asyncua/ua/uaerrors/_base.py
Makes typecheckers recognise the subclasses as Exceptions (#1204).
=> Make UaStatusCodeError subclass magic clearer and more concise.

asyncua/client/client.py
=> Strip Server Certificate from CA

asyncua/client/client.py
=> Handle server cert with clr in create_session

asyncua/client/client.py, asyncua/crypto/uacrypto.py, asyncua/server/server.py, tests/test_crypto_connect.py
Generates warning if a server application certificate or client certificate is not valid. This is to reduce issues/questions generate from invalid certificates.
=> Check application certificates

asyncua/common/subscription.py, asyncua/sync.py, tests/test_connections.py
See for details: https://github.com/FreeOpcUa/opcua-asyncio/discussions/1257
=> Adds missing method: status_change_notification

.github/dependabot.yml
=> Add complete dependabot config

asyncua/common/xmlparser.py
I tried to fixed the [issue 1324](https://github.com/FreeOpcUa/opcua-asyncio/issues/1324)
Please provide feedback if it is okay.
=> Fixed bug in xmlparser.py (Issue #1324)

asyncua/common/statemachine.py
I tried to fix [issue #1334](https://github.com/FreeOpcUa/opcua-asyncio/issues/1334)
Please provide feedback if it is okay.
=> Fixed state machine bug (Issue #1334)

schemas/generate_statuscode.py
=> Fix typo of the StatusCode name

asyncua/common/structures.py
=> Support pre 1.04 struct length fields for codesys

asyncua/ua/relative_path.py, tests/test_relative_path.py
Ref. https://github.com/FreeOpcUa/opcua-asyncio/pull/1382#issuecomment-1663215727.
=> Fixed to handle '#' and '&' as reserved char

asyncua/client/client.py, asyncua/sync.py
As pointed out in https://github.com/FreeOpcUa/opcua-asyncio/pull/1423#discussion_r1319602061. cc: @rth
=> Fix to use List as a return type of the methods

asyncua/ua/uatypes.py, tests/test_common.py
See #1436 
Maybe there are some issues with existing code. I tried to make a fallback, so old colde should work, as before.
=> bytestring nodeid as base64

asyncua/common/structures104.py
Instead of performing requests sequentially (awaiting asyncio coroutines in a loop) parallelize them with asyncio.gather functionality.
=> Recursive parse parallel crawl

asyncua/common/ua_utils.py
=> fixed wrong logger initialization

setup.py
=> bump cryptography to >40.0.1 in install_requires

asyncua/common/connection.py, asyncua/common/copy_node_util.py, asyncua/common/node.py, asyncua/common/structures104.py, asyncua/common/xmlexporter.py, asyncua/ua/uaerrors/_base.py
=> Replace assertions with a dedicated UaError

asyncua/common/manage_nodes.py
=> Change Encoding Object to Type

tests/test_sync.py
> This confirms @harriv's finding in #1313.
=> test: Verify loading from shelf files raises an AttributeError

asyncua/client/ha/ha_client.py
catch some more errors that can occur when trying to connect to a server that is not online
=> improve ha client keepalive error handling

dev_requirements.txt
https://github.com/pytest-dev/pytest/issues/12269
=> Bump pytest-asyncio to fix breakage

asyncua/common/subscription.py
=> set interval to 50 as default

asyncua/common/xmlimporter.py, tests/test_gen_certificates.py
The minimal example from https://github.com/FreeOpcUa/opcua-asyncio/issues/1722 as a unit test to see if fails or passes in CI.
Edit: Please let me know if you want such test, I don't have the impression that this combination is currently explicitly tested. Otherwise I can close this MR.
=> TST Add test to generate and load a private key

asyncua/common/xmlexporter.py, asyncua/common/xmlimporter.py, tests/custom_enum.xml, tests/custom_struct.xml, tests/test_common.py, tests/test_xml.py
Test cases to reproduce and a proposal to fix the bugs described in #1829
=> Fix: Issues with missing namespace URIs when importing and exporting XMLs

asyncua/common/structures.py
Add support for B&R. This solves https://github.com/FreeOpcUa/opcua-asyncio/issues/1825
=> Support pre 1.04 struct length fields for B&R
